### ISSUE TITLE
XML completion based on external DTD

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#106]

**Comment by NikolasKomonen** [comment]
@angelozerr Already working on it, almost done.

**Comment by angelozerr** [comment]
> @angelozerr Already working on it, almost done.

Really? You are implementing CMDocument like XML Schema, is that?

**Comment by NikolasKomonen** [comment]
Oh sorry, I got this confused. I'm not working on this.

**Comment by fbricon** [comment]
@NikolasKomonen  what's the status on that one? Can we target 0.0.3?

**Comment by angelozerr** [comment]
@fbricon I'm not sure that @NikolasKomonen is working on that, but if you think it's very important I could work on it.

**Comment by fbricon** [comment]
Having full Schema and DTD support would pretty much complete the validation stories. The rest is icing on the cake ;-)

**Comment by angelozerr** [comment]
Ok I will work on it.

**Comment by fbricon** [comment]
thanks @angelozerr!

**Comment by angelozerr** [comment]
@fbricon it should starts working (only completion for element and based on external DTD).

I will work for other features like completion on attribute, internal DTD (declared in the XML)

**Comment by angelozerr** [comment]
@fbricon completion for element and attributes based on external DTD should work (with tests too). For internal DTD it doesn't work yet. Should we create an another issue for that?
