### ISSUE TITLE
Adjust range for DTD Validation errors

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#107]

**Comment by angelozerr** [comment]
Could you attach your XML content in this issue please.

**Comment by fbricon** [comment]
```xml
<?xml version="1.0"?>
<!DOCTYPE note [
<!ELEMENT note (to,from,heading,body)>
    <!ELEMENT to (#PCDATA)>
        <!ELEMENT from (#PCDATA)>
                <!ELEMENT heading (#PCDATA)>
            <!ELEMENT body (#PCDATA)>
]>
<note>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend</body>
</note>
```

**Comment by angelozerr** [comment]
@fbricon should be fixed and with test too:)

**Comment by fbricon** [comment]
Yup it works.

Now we just need tests for  MSG_CONTENT_INCOMPLETE, MSG_REQUIRED_ATTRIBUTE_NOT_SPECIFIED, MSG_ATTRIBUTE_NOT_DECLARED, MSG_ATTRIBUTE_VALUE_NOT_IN_LIST so we can close that one

**Comment by angelozerr** [comment]
yes sure, if you can write it or just find sample like you have done previously, it should be very cool.

**Comment by fbricon** [comment]
There's 3:

```xml
<?xml version="1.0"?>
<!DOCTYPE note [
<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
]>
<note>
    <foo></foo>
    <from nope="">Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend</body>
</note>
```
<img width="777" alt="screen shot 2018-11-13 at 1 22 01 pm" src="https://user-images.githubusercontent.com/148698/48434221-238df400-e747-11e8-80c8-46edeacab318.png">

**Comment by fbricon** [comment]
Another issue (found while checking https://www.tutorialspoint.com/dtd/dtd_attributes.htm examples):
```xml
<?xml version = "1.0"?>
<!DOCTYPE address [
  <!ELEMENT address (company)*>
  <!ELEMENT company (#PCDATA)>
  <!ATTLIST company name NMTOKEN #FIXED "tutorialspoint">
]>
<address>
  <company name="etutorialspoint">we are a free online teaching faculty</company>
</address>
```
<img width="884" alt="screen shot 2018-11-13 at 1 37 44 pm" src="https://user-images.githubusercontent.com/148698/48435047-6e107000-e749-11e8-9a64-51b63140db3e.png">

**Comment by fbricon** [comment]
```xml
<?xml version = "1.0"?>
<!DOCTYPE foo [
  <!ELEMENT foo (bar)*>
  <!ELEMENT bar (#PCDATA)>
  <!ATTLIST bar fruit (one | two | three) #REQUIRED>
]>
<foo>
    <bar fruit="four">toto</bar>
</foo>
```
<img width="916" alt="screen shot 2018-11-13 at 1 52 30 pm" src="https://user-images.githubusercontent.com/148698/48435901-77024100-e74b-11e8-824a-eb2c49e81c39.png">


Feels like we'll still need to cover a ton of other errors, not listed in DTDErrorCode.java

**Comment by angelozerr** [comment]
> Another issue (found while checking https://www.tutorialspoint.com/dtd/dtd_attributes.htm examples):

WTP don't support it. lsp4xml supports it now.

> Now we just need tests for MSG_CONTENT_INCOMPLETE, MSG_REQUIRED_ATTRIBUTE_NOT_SPECIFIED, MSG_ATTRIBUTE_NOT_DECLARED, MSG_ATTRIBUTE_VALUE_NOT_IN_LIST so we can close that one

Done.

@fbricon  please close this issue if you think it's good and you find not another error whihc could be not supported. Thanks!

**Comment by angelozerr** [comment]
@fbricon thoses errors are for DTD content. I need parser

**Comment by fbricon** [comment]
Fair enough. Closing.
