### ISSUE TITLE
Autocompletion and hovers when writing XSDs

### ISSUE THREAD

**Issue by felixfbecker** [angelozerr/lsp4xml#111]
I am trying to get autocompletion while authoring an XSD.
For this, I declared the XSD as an instance of the XSD meta schema:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3.org/2001/XMLSchema
                               http://www.w3.org/2001/XMLSchema.xsd">

</xs:schema>
```

However, I am not getting any autocompletion or hovers.

Output channel log:

```
Sep 10, 2018 2:18:30 PM org.eclipse.lsp4xml.XMLLanguageServer initialize
INFO: Initializing LSP4XML server
```

(no errors)

Version: `vscode-xml-0.1.0-199.vsix`

**Comment by angelozerr** [comment]
I think it's because vscode-xml doesn't bind `.xsd` file extension to the XML Language Server.

Have you tried to rename your file with `.xml` extension?

**Comment by felixfbecker** [comment]
Ahh, yeah if I rename the file it works. `.Format.ps1xml` worked fine, so I thought it may only look for `<?xml` declaration at the top of files. In general I think it would be great if it did that instead of relying of the file extension, because there are many more file types that are XML but don't use a `.xml` extension, for example `.csproj`.

**Comment by angelozerr** [comment]
It's an issue for vscode-xml (client side). The XML Language Server doesn't use xml extension.

So please create an issue at https://github.com/redhat-developer/vscode-xml/issues, by listing all files extensions like xsd, xsl, csproj, etc

I close this issue since it's an issue of vscode-xml.

**Comment by fbricon** [comment]
@angelozerr does xsd support work correctly in LSP4E? See https://github.com/redhat-developer/vscode-xml/issues/22#issuecomment-419928374 and later comments

**Comment by angelozerr** [comment]
> @angelozerr does xsd support work correctly in LSP4E? See redhat-developer/vscode-xml#22 (comment) and later comments

No, same problem. I will investigate it.

**Comment by angelozerr** [comment]
@fbricon there are several problem that I'm fixing:

 * there are 3 xs:annotations. https://github.com/angelozerr/lsp4xml/commit/dbda60800a148dad30b8ae006142212f8d2ddcbb fixes a little this bug and now I have 2 xs:annotations. I continue to investiage the problem.
 * load of this XML Schema takes a very long time (sometimes one minute?). I don't know why, but its' a good usecase to support load of XML Schema which takes time.

**Comment by felixfbecker** [comment]
Are schemas cached on disk?

**Comment by angelozerr** [comment]
> Are schemas cached on disk?

Yes.

**Comment by angelozerr** [comment]
I have fixed the xs:annotation problme. Now you should have just one xs:annotation instead of 3.

**Comment by fbricon** [comment]
>> Are schemas cached on disk?

> Yes.
But it doesn't seem to survive a server restart.

We have #73 opened about caching schemas locally.

**Comment by felixfbecker** [comment]
I've also gotten it to work after waiting a very long time.

**Comment by angelozerr** [comment]
> I've also gotten it to work after waiting a very long time.

Ok now I see more better the problem, it should be cool @fbricon if you could help me to fix the problem.

I have the same problem with this XML file:

```xml
<web-app
        xmlns="http://xmlns.jcp.org/xml/ns/javaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee 
		 http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
        version="3.1">
</web-app>
```

There are 2 problem:

 * with validation
 * with completion

to work those 2 features correctly, I need to open the XML file and open completion and waits for around 1 minute without changing the editor content.

After that, XML Schema is cached. Today the XML Schema is loaded twice:

 * for validation and after it is set in cache by using XMLGrammarCachingConfiguration -> https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/contentmodel/participants/diagnostics/XMLValidator.java#L52

 * for completion and after it is set in cache -> https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/contentmodel/model/ContentModelManager.java#L121

The first improvement that we could do it is to load one time the XML Schema for completion and validation (we must study how xerces load the XML Schema for validation).

But the big improvement we should do it is to load the XML Schema in a Thread (with CompletableFuture?) and tell to user that this XML Schema takes time and it is loading (by adding a warn message in the XML top element) and avoid trying to load the XML Schema each time the user changes content inside XML editor.

@fbricon is there any chance that you could help me to implement this idea?

**Comment by felixfbecker** [comment]
I would suggest to not return a "warning" content but instead just delay the response to the hover. As long as the response is not there, a client will display "Loading...", but if you return a warning content, some clients cache the result and the user will never see the real content (Sourcegraph does this).

**Comment by angelozerr** [comment]
@felixfbecker I agree with you for hover, when I said "warning", I mean for diagnostics.

**Comment by angelozerr** [comment]
For performance problem (with some XML Schema), I have found it. See https://github.com/angelozerr/lsp4xml/issues/159 I will try to implement it.

**Comment by angelozerr** [comment]
@felixfbecker please reinstall last version of vscode, https://github.com/angelozerr/lsp4xml/issues/159 should fix your problem.

**Comment by angelozerr** [comment]
@fbricon I think we can close this issue, since https://github.com/angelozerr/lsp4xml/issues/159 should fix the performance problem.

**Comment by fbricon** [comment]
@angelozerr speed is now good, however I can't seem to get any hover result when editing an xsd file. Is it supposed to work?

**Comment by angelozerr** [comment]
> however I can't seem to get any hover result when editing an xsd file. Is it supposed to work?

It should work, another bug -(

**Comment by fbricon** [comment]
Let's close this one about completion. Hover will be handle in #192
