### ISSUE TITLE
Documentation on hover unnecessarily indented

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#115]
Hovering over the `<dependencies>` tag of a pom.xml, you can see the documentation is unnecessarily indented.

![screen shot 2018-09-10 at 11 59 09 pm](https://user-images.githubusercontent.com/148698/45337389-b9de4780-b555-11e8-9197-ab7bbfda5115.png)

**Comment by angelozerr** [comment]
Should be fixed now by normalizing spaces.
