### ISSUE TITLE
[Request] Document Hover

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#12]
Support hover over 
- [x] Tag
- [x] Attributes
- [ ] Values

**Comment by angelozerr** [comment]
Test was added, today only tag hover is supported, we need to support attribute name and value hover.

**Comment by fbricon** [comment]
So hover on attribute now works. Attribute enum values show the attribute doc though.

**Comment by angelozerr** [comment]
Indeed, I must implement it. My idea is tro try to search doc for value, if not found, I display doc for attribute name. Are you OK?

**Comment by fbricon** [comment]
sounds good
