### ISSUE TITLE
Comment should not be returned by documentSymbol

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#120]
documentSymbol returns comment and it can be confusing with element:

![image](https://user-images.githubusercontent.com/1932211/45441267-e661a300-b6be-11e8-9ec6-514e2cee6f6e.png)

To fix this issue, there are 3 solutions:

 1) display comments with other kind to see that it's a comment
 2) or remove it
 3) or  provide a preferences to return it or not.

@fbricon @NikolasKomonen what do you prefer?

**Comment by fbricon** [comment]
No, don't return comments. See the YAGNI principle. 
If someone requests it in the future, we can consider adding a flag then.

**Comment by angelozerr** [comment]
Thanks @fbricon for your answer. The isssue is fixed.
