### ISSUE TITLE
Autocompletion for attribute value

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#121]
Support Autocompletion for attribute value (based on XML Schema, DTD)

**Comment by angelozerr** [comment]
@fbricon @NikolasKomonen I have started to implement this feature, I must write tests and there is a bug which doesn't replace the whole attribute value. But it starts working, here a demo which shows you in action:

 * completion on attribute name based on XML Schema
 * completion on attribute value based on XML Schema
 * quick fix to replace attribute value if it's a boolean or an enumeration.

Here the demo:

![completiononattributevalue](https://user-images.githubusercontent.com/1932211/45501943-f5118e00-b782-11e8-83b6-05bdfa99798a.gif)

**Comment by fbricon** [comment]
@angelozerr what's the status on this one?

**Comment by angelozerr** [comment]
It's soon finished. It exists just a bug when completion is applied and you have typed some content.

**Comment by NikolasKomonen** [comment]
@angelozerr Think this is something I can work on?

**Comment by angelozerr** [comment]
> @angelozerr Think this is something I can work on?

Yes sure!

**Comment by NikolasKomonen** [comment]
@angelozerr Is this issue fixed. If not, what is the case for:

>a bug when completion is applied and you have typed some content.

**Comment by angelozerr** [comment]
> @angelozerr Is this issue fixed. If not, what is the case for:

It seems that it is fixed. I close the issue.
