### ISSUE TITLE
No autocompletion until the root element is added

### ISSUE THREAD

**Issue by felixfbecker** [angelozerr/lsp4xml#123]
I associated a schema via a file pattern:
```json
"xml.fileAssociations": [
    {
      "systemId": "https://raw.githubusercontent.com/felixfbecker/PowerShellXSD/master/Format.xsd",
      "pattern": "**/*.Format.ps1xml"
    }
  ]
```

When I create a new file, I do not get any autocompletion for
- The xml declaration and its attributes
  - Ideally this should suggest a snippet where `version` defaults to `1.0` and `encoding` to `utf-8`
- The root element (despite it being know through the file association)

![2018-09-14 18 06 39](https://user-images.githubusercontent.com/10532611/45561942-3cfae880-b849-11e8-8d61-a0448b7d4a90.gif)

**Comment by NikolasKomonen** [comment]
> xml declaration and its attributes

Right now the xml declaration doesn't have completion setup, I'll be getting to that soon.

>The root element

Personally not sure about that one

**Comment by angelozerr** [comment]
> xml declaration and its attributes

@NikolasKomonen has intention to do. See https://github.com/angelozerr/lsp4xml/issues/85

> The root element (despite it being know through the file association)

I will do it. I affect me this issue since the root element doesn't work. For the xml declaration compeltion, please see https://github.com/angelozerr/lsp4xml/issues/85

**Comment by angelozerr** [comment]
@felixfbecker it should work now but only if you type '<'. I will see if it's easy to to that with ctrl+space only.

**Comment by angelozerr** [comment]
@felixfbecker it should work now with ctrl+space too (without typing '<')
