### ISSUE TITLE
Language server cannot find schema after a while

### ISSUE THREAD

**Issue by felixfbecker** [angelozerr/lsp4xml#126]
After I leave a file open in the background for a while, then come back to it, I often see that the root element is not recognised anymore. Restarting solves it, so it cannot be a problem with the schema.

![2018-09-14 18 34 12](https://user-images.githubusercontent.com/10532611/45563212-f9a27900-b84c-11e8-85a9-d02322603f9e.gif)

**Comment by angelozerr** [comment]
@felixfbecker have you 2 file associations?

**Comment by angelozerr** [comment]
@felixfbecker there were a bug when there were 2 xml filer assocoiations. Ho^pe it's your case.

**Comment by felixfbecker** [comment]
These are my settings:
```json
"xml.fileAssociations": [
    {
      "systemId": "https://www.w3.org/2001/XMLSchema.xsd",
      "pattern": "**/*.xsd"
    },
    {
      "systemId": "https://raw.githubusercontent.com/felixfbecker/PowerShellXSD/master/Format.xsd",
      "pattern": "**/*.Format.ps1xml"
    },
    {
      "systemId": "https://raw.githubusercontent.com/felixfbecker/PowerShellXSD/master/Types.xsd",
      "pattern": "**/*.Types.ps1xml"
    }
  ],
```

**Comment by fbricon** [comment]
@angelozerr testing with IBM's examples, I can't get file association to work with 
```json
"xml.fileAssociations": [{
    "systemId": "file_association/invoice.xsd",
    "pattern": "*/file_association/invoice_*.xml"
},
```

**Comment by angelozerr** [comment]
> These are my settings:

Great, I think it's the case I have fixed.

> @angelozerr testing with IBM's examples, I can't get file association to work with

I will try to investigate the problem.

**Comment by angelozerr** [comment]
Perhaps yes, but to be honnest with you, I don't know, I have implemented file association quickly.

**Comment by fbricon** [comment]
@angelozerr ok. I opened #142 to follow up on that issue.

**Comment by angelozerr** [comment]
> @angelozerr ok. I opened #142 to follow up on that issue.

Thanks.

@felixfbecker could you tell me if your problem is resolved please.

**Comment by felixfbecker** [comment]
I get autocompletion for the top-level element:

![image](https://user-images.githubusercontent.com/10532611/46000716-a250a400-c0a9-11e8-8003-4a1d40f47b06.png)

But I don't get autocompletion for the `<?xml` header:

![2018-09-25 09 59 34](https://user-images.githubusercontent.com/10532611/46000764-cb713480-c0a9-11e8-9686-f1e14cdb1f7d.gif)

**Comment by angelozerr** [comment]
> I get autocompletion for the top-level element:

This issue is not for that. The well issue is https://github.com/angelozerr/lsp4xml/issues/123 and I must improve it to have top-level element with ctrl+space

> But I don't get autocompletion for the <?xml header:

This issue is not for that. And it's normal because @NikolasKomonen has not implemented https://github.com/angelozerr/lsp4xml/issues/85

The original  issue is about `After I leave a file open in the background for a while, then come back to it, I often see that the root element is not recognised anymore.` Have you again the problem?

**Comment by felixfbecker** [comment]
Oh, sorry I confused issues. I've not seen that problem again, but I've also not used it for a long time since then. I can reopen this if it occurs again.
