### ISSUE TITLE
Format no joinContentLines doesn't work with \r\n

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#131]
Format no joinContentLines doesn't work with \r\n. Tests are not passed in this case.

**Comment by angelozerr** [comment]
@NikolasKomonen I have fixed the problem. I have several comments about your work:

 * if you add StringUtils method, please add tests too. The StringUtils method should be simply and not linked to a context (like your old rTrimOffset which requires a startOffset, in this case rTrimOffset should be in private where your code is used). 

 * write test : I have simplify your code to use trimNewLines https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/utils/StringUtils.java#L74 and add test at https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/utils/StringUtilsTest.java

Hope I have not broken something.

**Comment by NikolasKomonen** [comment]
@angelozerr Thanks for the comments I'll make sure to consider this for the future. And nothing seems to have been broken.
