### ISSUE TITLE
Experimental Incremental support

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#133]
In large XML file, vscode like Eclipse freezes as soon as you type something. One of problem is because the didChange command send a big JSON content every time.

One idea that I have is to se the Incremental support on the server side, and didChange update the string of stored TextDocument.

I have started to implement this idea, but I think we should have a preferences like "experimentalIncrementalSupport" because I fear that there are some bugs.

@fbricon @NikolasKomonen what do you think about this experimentalIncrementalSupport preferences?

**Comment by fbricon** [comment]
Yes, that'd be interesting, but I think `experimental.incrementalSupport.enabled` would be better.
Also, it'd be nice to finish getting proper schema validation/completion support before we start adding new fancy features.

**Comment by fbricon** [comment]
So I tried to test it in vscode but the way you implemented it, it's not a preference, but a client capability. In vscode we don't have an easy access to tweak available client capabilities and add experimental stuff.
The ClientCapabilities.experimental property is meant to add experimental feature of the protocol.

I think the experimental property *you* want needs to be part of the server configuration, i.e sent in the "settings" section of  InitializeParams#getInitializationOptions(), so eventually ends up in XMLClientSettings

**Comment by angelozerr** [comment]
> so eventually ends up in XMLClientSettings

Done.

**Comment by angelozerr** [comment]
IMHO I think we should try to activate this incremental support to fix 

 * https://github.com/angelozerr/lsp4xml/issues/324
 * and perhaps https://github.com/angelozerr/lsp4xml/issues/48

The basic idea of incremental support is to update the XMLDocument text String  content from DidChangeTextDocumentParams (which is filled only with text changed and not with the whole document in the case of activated incremental support ) -> see
https://github.com/angelozerr/lsp4xml/blob/a77306975b2312a1a219789a8d437d44064e59d8/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/commons/TextDocuments.java#L86

We need to write a lot of test with call of update method: 
https://github.com/angelozerr/lsp4xml/blob/a77306975b2312a1a219789a8d437d44064e59d8/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/commons/TextDocument.java#L133

**Comment by NikolasKomonen** [comment]
@angelozerr Is my following understanding of incremental support correct? 

1) The client will send the changed characters instead of the whole document

2) The server will insert all of the changes into the current document

3) The server will re-parse the **whole** document

So all incremental support is doing is reducing the size of the didChangeTextDocument json?

**Comment by fbricon** [comment]
yes that's pretty much it

**Comment by angelozerr** [comment]
@NikolasKomonen it's exactly that!
