### ISSUE TITLE
Code action to close missing quotes for attributes

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#137]

**Comment by NikolasKomonen** [comment]
Follow : https://github.com/angelozerr/lsp4xml/tree/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/contentmodel/participants/codeactions

**Comment by angelozerr** [comment]
@NikolasKomonen I suggest you to see https://github.com/angelozerr/lsp4xml/commit/492212a08cd47fcc96a347d59a4a7fe58c2a2c58

**Comment by NikolasKomonen** [comment]
@angelozerr We can close this?

**Comment by angelozerr** [comment]
Me i have not implemented That but i Can Do it if you wish

**Comment by fbricon** [comment]
Not sure this is a critical missing piece. It's as fast to add the missing quote manually, if not faster

**Comment by NikolasKomonen** [comment]
@angelozerr what do you think about 

> Not sure this is a critical missing piece. It's as fast to add the missing quote manually, if not faster

Think we can close this?

**Comment by angelozerr** [comment]
> Think we can close this?

No please, it's implemented in few minutes, I will do it.
