### ISSUE TITLE
File association should support relative path for systemId

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#142]
right now, trying to validate the [examples](https://github.com/microclimate-devops/xml-language-server/blob/master/sample-resources/file_association/invoice_with_errors.xml) from IBM's XML language server by associating files like:
```json
"xml.fileAssociations": [{
    "systemId": "file_association/invoice.xsd",
    "pattern": "**/file_association/invoice_*.xml"
},
```
has no effect. I tried using an absolute path for systemId but didn't work either (tried on a Mac)

**Comment by fbricon** [comment]
so absolute path actually works but I had to restart the server to get it working.

Also, after using a relative path and restarting the server, I get a bunch of errors like:

schema_reference.4: Failed to read schema document 'file_association/invoice.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

**Comment by angelozerr** [comment]
@fbricon please tell me if it works for you.

**Comment by fbricon** [comment]
Works for `**/file_association/invoice_*.xml`. Not for `*/file_association/invoice_*.xml` (the syntax in IBM's example). Not sure if it's a big deal

**Comment by angelozerr** [comment]
The IBM Language Server uses regexp to do that. In my case I'm using glob pathmatcher. I'm not sure if we should support  IBM Language Server syntax too.

**Comment by fbricon** [comment]
It's probably fine as-is
