### ISSUE TITLE
Changing the file associations or catalogs in the preferences should trigger validation

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#143]
When a file association or a catalog is added or modified in the preferences, if a matching document is already open, it doesn't take into account the new schema.
Either diagnostics on opened documents are stale or missing.
So changing associations or catalogs should trigger validation for all opened documents.

**Comment by angelozerr** [comment]
Changing content of XML Schema/DTD should trigger too validation. We could start to trigger validation for all opened XML document and after we could improve it to validate only XML document which is linked to the XML Schema/DTD which changed.

**Comment by angelozerr** [comment]
It should work. We need to write tests.

**Comment by angelozerr** [comment]
It should work now, please give me feedback.

**Comment by fbricon** [comment]
I confirm this works. Do we have regression tests for that?

**Comment by angelozerr** [comment]
No taht's why I have not closed it
