### ISSUE TITLE
No validation when referencing a schema  in the same directory

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#144]
Trying the example in https://stackoverflow.com/a/8780114/753170

resources.xsd:
```xml
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="property">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="resource">
        <xs:sequence>
            <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="resources">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resource" type="resource" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="variant" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
```
and resources.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="resources.xsd"
        variant="X">
    <resource name="res00" >
        <property name="propA" value="..." />
        <property name="propB" value="..." />
    </resource>
    <resource name="res01" >
        <property name="propA" value="..." />
        <property name="propB" value="..." />
    </resource>
</resources>
```

resources.xml has an error on the opening resources tag:
> cvc-elt.1.a: Cannot find the declaration of element 'resources'.

**Comment by fbricon** [comment]
I still have the error, but completion for resource nodes and attributes work as expected. Weird

**Comment by angelozerr** [comment]
I'm sorry @fbricon I cannot reproduce?

**Comment by angelozerr** [comment]
@fbricon this issue is annoying because it works for me on Windows OS and tests https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/extensions/contentmodel/XMLSchemaDiagnosticsTest.java#L202 is passing.

@NikolasKomonen have you the same problem?

**Comment by angelozerr** [comment]
@fbricon I can reproduce your issue!

To reproduce your problem, you need to open 2 XML files which are linked to an XML Schema which have no target namespace: 

 * for instance open the invocie.xml. It stores in Xerces cache the XML Schema invoice.xsd with target namespace null as key (it's Xerces code)
 * open the resources.xml, it uses the ML Schema invoice.xsd  that's why you have your bug.

To fix this bug, we need not to use Xerces cache. If you replace in XMLValidator, the line 50 

`XMLParserConfiguration configuration = new XMLGrammarCachingConfiguration();`

with 

`XMLParserConfiguration configuration = new XIncludeAwareParserConfiguration();`

Your bug dispareas, but we losse cache feature -( I would liek to keep cache feature, no find a solution for the moment.

**Comment by angelozerr** [comment]
As WTP uses XIncludeAwareParserConfiguration, I decide to do the same thing.

@fbricon tell me if it fixes your problem.

**Comment by fbricon** [comment]
can't we bind one parserconfiguration to one document? so that caching would be scoped to that particular document

**Comment by angelozerr** [comment]
@fbricon I cannot fix this issue since I cannot reproduce it -( I will try to understand how I could reproduce the problem

> can't we bind one parserconfiguration to one document? so that caching would be scoped to that particular document

Yes we could do that, but performances seems good, we will see if we need that in the future.

**Comment by angelozerr** [comment]
> Sanitizing the rootUri fixes this issue.

I don't understand, it should not be linked? I have fixed rootURI for file associations, but I'm sceptical that it fixes this issue? Please give me feedback.

**Comment by fbricon** [comment]
You're right, this is irrelevant. It's working for me now anyway.
