### ISSUE TITLE
Validation of empty required node shows misplaced diagnostics

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#145]
With the same old invoice document, when adding empty tags that are required, the diagnostics are put under the closing bracket. Also the 1st empty tag is underline:
![sep-25-2018 18-09-12](https://user-images.githubusercontent.com/148698/46046335-a94dd580-c0ee-11e8-8b5a-bf7123780a09.gif)

**Comment by angelozerr** [comment]
@fbricon please tell me if it's OK now.

**Comment by fbricon** [comment]
Works fine now, thanks @angelozerr
