### ISSUE TITLE
Add support for `textDocument/definition` for XML Schema

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#148]
So that you can navigate from an element to its type definition in a schema. 
Suggested by @ifedorenko.

**Comment by angelozerr** [comment]
I love this idea, but I'm afraid that it's an hard work. @ifedorenko is there any chance that you could work on this feature? If yes, tell me and I will initialize support extension for definition, that you will able to implement it in `extensions/contentmodel`.

**Comment by ifedorenko** [comment]
no, I do not currently plan to work on this enhancement.

**Comment by angelozerr** [comment]
> no, I do not currently plan to work on this enhancement.

Ok thanks for your answer. I have initialized the definition participant.

**Comment by angelozerr** [comment]
I would like to try to manage those defintion type with XPath with #168. The idea is just to declare references with Xpath between type, ex : 

```
from="//*:extension/@base"
to="//*:complexType/@name"
```

If we take this sample

```xml
<xs:element name="employee" type="fullpersoninfo"/>

<xs:complexType name="personinfo">
  <xs:sequence>
    <xs:element name="firstname" type="xs:string"/>
    <xs:element name="lastname" type="xs:string"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="fullpersoninfo">
  <xs:complexContent>
    <xs:extension base="personinfo">
      <xs:sequence>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="city" type="xs:string"/>
        <xs:element name="country" type="xs:string"/>
      </xs:sequence>
    </xs:extension>
  </xs:complexContent>
</xs:complexType>
```

the below XPath from/to declaration will manage

 * completion
 * hyperlink
 * references
 * validation

**Comment by angelozerr** [comment]
Thank's @NikolasKomonen for your review!
