### ISSUE TITLE
Formatting node content inserts new line without proper indentation

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#152]
When "format.joinContentLines":false, formatting a node with text in it puts the text in the next line, with no indentation:

![bad-format](https://user-images.githubusercontent.com/148698/46210338-7417d200-c2fe-11e8-8eba-086ab8a0c319.gif)

Both Eclipse and IntelliJ keep the text at the same place. If a new line was to be inserted (which I'm really not sure about), at least some proper indentation should be used.

**Comment by fbricon** [comment]
I actually think adding a new line is wrong, as it definitely changes the data value

**Comment by NikolasKomonen** [comment]
@fbricon 

Would a result of

```
<property> some test data
</property>
```

be the best option?

**Comment by NikolasKomonen** [comment]
@apupier 
So

```
<a> My

Text

Content</a>
```

should remain as it is when formatted?

Instead of:

```
<a> My

Text

Content
</a>
```
