### ISSUE TITLE
More detailed completion for prolog

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#155]
Completion Items for these prolog elements:

- version attribute name
- version attribute value (1.0, 2.0)
- encoding attribute name
- encoding attribute value (UTF-8, UTF-16, etc)

**Comment by fbricon** [comment]
Completion should also propose the `standalone` attribute, with values `yes` or `no`. See https://www.ibm.com/support/knowledgecenter/en/SSMKHH_10.0.0/com.ibm.etools.mft.doc/ac67224_.htm
