### ISSUE TITLE
Completion for xsi attributes

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#163]
Add completion for xsi attributes:

 - `schemaLocation`
 - `noNamespaceSchemaLocation`
 -  `nil`?

See https://www.w3.org/TR/xmlschema-1/#d0e3067

**Comment by NikolasKomonen** [comment]
@angelozerr Think I can work on this?

**Comment by angelozerr** [comment]
yes sure!

**Comment by NikolasKomonen** [comment]
@angelozerr Would you recommend I create a new IXMLExtension implementation for this issue. Or should I put it into an existing class like ContentModelPlugin or XMLReferencesPlugin?

**Comment by angelozerr** [comment]
ContentModelCompletionParticipant is  good I think.

**Comment by angelozerr** [comment]
> read from https://www.w3.org/2001/XMLSchema-instance

You mean using an XML Schema? If it exists an XML Schema for XMLSchema-instance it should be cool to use it, otherwise we need to hard coded that (I think we should do that, but please check that it exists a XMLSchema-instance XML Schema).

**Comment by NikolasKomonen** [comment]
@angelozerr I found that https://www.w3.org/2001/XMLSchema-instance == https://www.w3.org/2001/XMLSchema-instance.xsd . If you use a web browser to view the page source it has the xsd.

Im trying to use [the loader here](https://github.com/angelozerr/lsp4xml/blob/8a5444e05f5c010f1048d31f7d43dabafd6a3ca2/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/model/ContentModelManager.java#L139) with one of the above URI's but it doesnt seem to work.

Do you think it will take a lot more work to get it working?

**Comment by angelozerr** [comment]
An interesting topic about this XMLSchema is https://stackoverflow.com/questions/17094247/where-is-the-xsd-file-for-http-www-w3-org-2001-xmlschema-instance

You can view source of this XML Schema  with Chrome: `view-source:https://www.w3.org/2001/XMLSchema-instance` but it says 

`This schema should never be used as such: the XML Schema Recommendation forbids the declaration of attributes in this namespace
`

So I think we shouldhard coding this completion and perhaps validation too?

**Comment by NikolasKomonen** [comment]
@angelozerr  I agree, hard coding should be good. I'll work on completion for now.

**Comment by angelozerr** [comment]
> I'll work on completion for now.

Very cool! Thanks!
