### ISSUE TITLE
Incomplete autocompletion for xsl documents

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#165]
Given 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:|
</xsl:stylesheet>
```
There's no autocompletion result for `xsl:template`, even though some other items are proposed:

<img width="684" alt="screen shot 2018-10-17 at 4 09 20 pm" src="https://user-images.githubusercontent.com/148698/47113479-29b3b200-d227-11e8-9443-5df67381745b.png">

**Comment by fbricon** [comment]
@angelozerr any idea why?

**Comment by angelozerr** [comment]
> @angelozerr any idea why?

Yes I see the problem, `xsl:declaration` is marked as `abstract ` 

```xml
<xs:element name="declaration" type="xsl:generic-element-type" abstract="true"/>
```
and `template` is marked as `substitutionGroup="xsl:declaration"`

```xml
<xs:element name="template" substitutionGroup="xsl:declaration">
```

In other words, xsl:declaration must not be returned by completion, but template, and other element marked with  `substitutionGroup="xsl:declaration"` must be returned.

Fix will come soon.
