### ISSUE TITLE
[regression] schema file association no longer works with relative paths

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#174]
With the latest vscode-xml build and with IBM's file association examples, when using:

```json
"xml.fileAssociations": [
        {
            "systemId": "file_association/invoice.xsd",
            "pattern": "**/file_association/invoice_*.xml"
        },
    ],
```

The validation of files under `/Users/fbricon/Downloads/sample-resources 3/` fails with:
 
[xml] cvc-elt.1.a: Cannot find the declaration of element 'invoice'. [cvc-elt.1.a]
[xml] schema_reference.4: Failed to read schema document 'file:///Users/fbricon/Downloads/file_association/invoice.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>. [schema_reference.4]

The server is looking for the schema one folder up from the actual working directory. 
This used to work properly before.

**Comment by angelozerr** [comment]
I have tried to fix it, please tell me if it works better.

**Comment by fbricon** [comment]
@angelozerr nothing changed. Still showing the exact same errors

**Comment by angelozerr** [comment]
I'm not sure, but I suspect problem comes from https://github.com/angelozerr/lsp4xml/issues/142

**Comment by angelozerr** [comment]
@fbricon could you give me a screenshot of your vscode to see which folder is your working directory, and try to have the same condition than you (I cannot reproduice it). Thanks!

**Comment by angelozerr** [comment]
My question is what is your rootUri?:

 - `/Users/fbricon/Downloads/sample-resources 3/`
 - or` /Users/fbricon/Downloads`

It seems your root uri is `/Users/fbricon/Downloads`. 

In LSP4e, I have an Eclipse project "sample-resources 3" linked to `/Users/fbricon/Downloads/sample-resources 3/` and my rootUri is  ` /Users/fbricon/Downloads/sample-resources 3` so after concatenation, I have the well XML Schema  `/Users/fbricon/Downloads/sample-resources 3/file_association/invoice.xsd`

**Comment by angelozerr** [comment]
@fbricon I cannot fix this issue since I cannot reproduce it -( I will try to understand how I could reproduce the problem

**Comment by fbricon** [comment]
I tracked the issue to XMLFileAssociationResolverExtension.expandSystemId(). The rootUri is correct, but Xerces' XMLEntityManager.expandSystemId computes the expandSystemId to one folder up the root directory:
<img width="1139" alt="screen shot 2018-10-31 at 1 26 55 am" src="https://user-images.githubusercontent.com/148698/47767967-60201100-dcac-11e8-80fc-2c3b634ee9d8.png">

**Comment by fbricon** [comment]
The problem seems to be caused by rootUri lacking the ending slash. If the root uri is sanitized to add that missing `/`, it works.

**Comment by angelozerr** [comment]
Thanks for your feedback @fbricon ! I will try to have the same context than you and fix the problem.

**Comment by angelozerr** [comment]
@fbricon I have fixed the problem for file associations and write tests. Tell me if it works now for you.

**Comment by fbricon** [comment]
So relative path works now for file association, but then, in some cases, not all, I run into #180. Will try to provide more context on that bug
