### ISSUE TITLE
Cache doesn't seem to work for web.xml

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#176]
With the following web.xml:
```xml
<web-app
        xmlns="http://xmlns.jcp.org/xml/ns/javaee"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee 
		 http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
        version="3.1">

</web-app>
```
validation is very slow to kick in. Every time the vscode-xml extension is restarted, the 1st time the web.xml is accessed, it's still super slow. Looks like it doesn't leverage the caching mechanism (no web-app_3_1.xsd stored in ~/.lsp4xml).

Moreover, once the validation eventually kicks in, autocompletion doesn't provide the expected results. You need to close/reopen the file for it to work.

**Comment by angelozerr** [comment]
@fbricon have you enabled useCache? By default cache is not enabled.

**Comment by fbricon** [comment]
Damn, got bitten, **again**, by useCache not being turned on by default. We should definitely enable it by default.
