### ISSUE TITLE
No completion nor validation when editing an xsd schema

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#178]
```xml
<?xml version="1.1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
   <xs:  <!-- no completion here -->
   <foo>bar</foo> <!-- no error here -->
</xs:schema>
```

**Comment by ehigiepaul** [comment]
same here too.

**Comment by angelozerr** [comment]
I'm working on this issue.

**Comment by fbricon** [comment]
8967764 doesn't fix this issue for the moment

**Comment by angelozerr** [comment]
@fbricon you must wait for around 1 minutes before having validation and completion (it's not usable)

**Comment by angelozerr** [comment]
Sorry @fbricion, I have not seen that you have not specify some namespace. I'm supporting this feature, a commit will come soon.

**Comment by angelozerr** [comment]
@fbricon please retry, it should work and if you disable cache, it should be fast too since XML Schema is deployed from classpath.

**Comment by fbricon** [comment]
Works nicely now, thanks!

**Comment by fbricon** [comment]
even when working offline without any cache. Closing.

**Comment by angelozerr** [comment]
@fbricon test passed now, I think this issue can be closed, please give me feedback.

**Comment by angelozerr** [comment]
Thanks @fbricon for your feedback.
