### ISSUE TITLE
Provide information on POM 'properties' variables

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#183]
In a pom if a property is defined:

```
<properties>
  <variable.name> Value </variable.name>
</properties>
```

allow the user to see value of:

```
<project>${variable.name}</project>
```

through maybe a hover or go to definition.

**Comment by angelozerr** [comment]
I love this idea. This feature should be hosted in teh pom.xml extension plugin https://github.com/angelozerr/lsp4xml/issues/166

**Comment by fbricon** [comment]
Again, this requires loading the Maven models and inspecting them to compute the property values. See https://github.com/angelozerr/lsp4xml/issues/166#issuecomment-433720444

**Comment by angelozerr** [comment]
For maven support with LSP4XML, please create issues at https://github.com/angelozerr/lsp4xml-extensions-maven
