### ISSUE TITLE
Validate XML Schema

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#190]
It should be cool to validate XML Schema types. takes a sample like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="person">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="XXXXXX" />
				<xs:element name="prenom" type="xs:string" />
				<xs:element name="date_naissance" type="xs:date" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
```

Eclipse WTP XML Editor display those following errors:

![image](https://user-images.githubusercontent.com/1932211/47932354-af935680-ded1-11e8-9fef-984a1189de2c.png)

**Comment by angelozerr** [comment]
@fbricon this issue starts working:

![image](https://user-images.githubusercontent.com/1932211/47997220-64f52280-e0fb-11e8-8f61-ec046b0ca3b4.png)

I'm writing tests and after I will able to commit my work, can I do that or you prefer creating release before?

**Comment by fbricon** [comment]
Open a PR, that way we can test it and if safe to merge before the release, then we'll do that

**Comment by angelozerr** [comment]
When you think you could do the release?

**Comment by fbricon** [comment]
Depends on @NikolasKomonen. Hopefully later today or tomorrow, once everything is done. See https://waffle.io/redhat-developer/vscode-xml?milestone=v0.0.2,0.2.0

**Comment by angelozerr** [comment]
@fbricon I have commited my work but XSD validator is not enable . 

If you want to play with it, you must just uncomment https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/xsd/participants/diagnostics/XSDDiagnosticsParticipant.java#L38

**Comment by fbricon** [comment]
I'd have preferred you opened a PR. That commit contains significant changes, even if it's not enabled by default

**Comment by angelozerr** [comment]
> I'd have preferred you opened a PR. That commit contains significant changes, even if it's not enabled by default

DO you want I revert my work?

**Comment by angelozerr** [comment]
> I'd have preferred you opened a PR. 

Sorry @fbricon I will do it next time -(

**Comment by angelozerr** [comment]
@fbricon I'm writting test for this feature. Do you think I can enable it once test will be finished or you prefer waiting for creating release 0.2 before I activate it.

**Comment by fbricon** [comment]
go ahead. If it breaks something, we'll revert before releasing

**Comment by angelozerr** [comment]
> go ahead. If it breaks something, we'll revert before releasing

After writing tests, I have seen that there is some trouble, so I prefer not enabling the XSD validation. I must  study more Xerces source code to understand the problem. In other words you can create release now if you wish.
