### ISSUE TITLE
Completion from local xsd seems cached too agressively

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#194]
Given an xml document:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<resources variant="foo" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resources.xsd">
    <resource name="res00" >
        <property name="propA" value="..." />
        <property name="propB" value="..." />
    </resource>
    <resource name="" >
        <property name="" value="..." />
        <property name="" value="..." />
    </resource> 
</resources>
```
and its resources.xsd:
```xml
<?xml version="1.0"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="property">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="resource">
        <xs:sequence>
            <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="resources" type="resources">
        
    </xs:element>
    <xs:complexType name="resources">
            <xs:sequence>
                <xs:element name="resource" type="resource" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="variant" type="xs:string" use="required"/>
        </xs:complexType>
</xs:schema>
```

If you remove `variant="foo"` from the xml doc, a validation error pops up, as expected. Completion within the resources node shows you can add `variant`.
Now if you modify resources.xsd, rename `variant` into `something`, save the file, then make a change in the xml document, you'll see 2 errors, as expected: 
- cvc-complex-type.4: Attribute 'something' must appear on element 'resources'.
- cvc-complex-type.3.2.2: Attribute 'variant' is not allowed to appear in element 'resources'.

Remove the `variant` attribute from `<resources` and autocomplete to get the new attribute: `variant` is still shown, not `something`. Closing/reopening all documents don't change anything, the old attribute name is definitely cached in memory. Only way to get past it is to restart the server.

**Comment by angelozerr** [comment]
Indeed @fbricon I know this problem. It's because cache is done for completion in a very very basic mean at https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/model/ContentModelManager.java#L138

To fix this issue, we should check if file last modified has changed (the first step), but XML Schema can be too an URL (we could considerer to cache without checking last modified).

Check last modified of the XML Schema to disable cache, will work for your resources.xsd, but if the XML Schema include a B.xsd XML Shema, we must check too that B.xsd last modified has changed.

An another very simple solution is not to cache XML Schema.

**Comment by fbricon** [comment]
Depends if not caching local schemas has a big impact on perf

**Comment by angelozerr** [comment]
> Depends if not caching local schemas has a big impact on perf

It's like validation (which doesn't use cache now). If XML Schema is on file system, it's fast.

**Comment by fbricon** [comment]
so +1 to not caching local schema files. Remore URLs should be cached though

**Comment by fbricon** [comment]
A more robust solution could be implemented later, that'd support remote schemas

**Comment by angelozerr** [comment]
@fbricon I have removed cache for completion. Your usecase should work now. We need to write tests for that.

**Comment by fbricon** [comment]
Yes I confirm it works. Please add the tests so we can close it

**Comment by angelozerr** [comment]
> Yes I confirm it works. Please add the tests so we can close it

Done.
