### ISSUE TITLE
[regression] catalog support broken by cache download

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#195]
Initially opened in https://github.com/redhat-developer/vscode-xml/issues/78:

> Testing the good old IBM examples https://raw.githubusercontent.com/microclimate-devops/xml-language-server/master/client-vscode/xml-client/readme-resources/examples.zip, I get no errors, but that diagnostic that won't go away:
<img width="679" alt="screen shot 2018-11-05 at 11 55 37 am" src="https://user-images.githubusercontent.com/148698/48013215-d0d28d80-e0f1-11e8-99ff-70172c9da825.png">

>  I set 

```json
    "xml.catalogs": [
        "catalog/catalog.xml"
    ],
``` 

to which @angelozerr replied

> The problem comes from cache resolver which is executed before catalog te resolver. More there is à bug with cache when download fails. Validation is triggered every time.

**Comment by angelozerr** [comment]
I will Work on this issue

**Comment by angelozerr** [comment]
@fbricon this bug should be fixed and I write tests for that. Hope tests will work with travis.

**Comment by fbricon** [comment]
Nope
<img width="721" alt="screen shot 2018-11-06 at 10 02 45 am" src="https://user-images.githubusercontent.com/148698/48072737-39ca0c00-e1ab-11e8-825e-c6c241f2fb76.png">

Catalog should be used instead

**Comment by fbricon** [comment]
using
```json
"xml.catalogs": [
        "catalog/catalog.xml"
    ],
```

**Comment by angelozerr** [comment]
I have written a test for that at https://github.com/angelozerr/lsp4xml/commit/2a67ab48a16b1b898be258366130d24ea9d75321#diff-0a00a499003b9792b559241093ba0ebbR87 it should work, perhaps it's a catalog configuration problem?

**Comment by angelozerr** [comment]
I think the problem is that catalog path must be a file catalog 

```
"xml.catalogs": [
        "C:/catalog/catalog.xml"
    ],
```

In your case, it seems that you wish lsp4j use rootUri, is that?

**Comment by fbricon** [comment]
yes. it used to work

**Comment by fbricon** [comment]
Even when using an absolute path, the validation fails to work. Even though ContentModelManager.isXMLCatalogFileValid return true

**Comment by angelozerr** [comment]
That's strange it works for me? Could you debug XMLCatalogResolverExtension#resolveEntity please.

**Comment by fbricon** [comment]
I've rebuilt with the latest commit and it works now with an absolute path. XMLCatalogResolverExtension.resolveEntity did resolve before

**Comment by fbricon** [comment]
works with relative path now too. I'm confused

**Comment by fbricon** [comment]
Anyways, I'm closing the issue since it now works
