### ISSUE TITLE
CacheResourcesManager keeps trying to download unavailable resources

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#201]
When a non existing schema is used, CacheResourcesManager will keep on hitting the bad url on every keystroke.

Failed caching queries should be cached themselves (5 minutes?), so as to avoid unnecessary http requests.

**Comment by angelozerr** [comment]
@fbricon is there any chance that you work on this issue? I'm very busy with DTD support issues.

**Comment by fbricon** [comment]
@NikolasKomonen can look into it once he's done with his stuff

**Comment by angelozerr** [comment]
Great! Thanks
