### ISSUE TITLE
XSD Completion is a noticeably slower

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#203]
See the lsp4xml pom.xml now 
![slow](https://user-images.githubusercontent.com/148698/48146988-440c0900-e284-11e8-9742-0c899ff45bee.gif)

vs when using the previous 0.0.1:
![fast](https://user-images.githubusercontent.com/148698/48146977-3bb3ce00-e284-11e8-8a13-8204a1a31288.gif)

**Comment by fbricon** [comment]
@angelozerr can you fix it?

**Comment by angelozerr** [comment]
Done quickly, hope it will work.

**Comment by fbricon** [comment]
We're back to having a snappy completion. Thanks @angelozerr !
