### ISSUE TITLE
Provide automatic completion/validation in catalog file

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#204]
Ideally, we should get completion in catalog files:
```xml
<?xml version="1.0"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    //Should provide completion here
</catalog> 
```

**Comment by angelozerr** [comment]
To do that we must return the well XML Schema according the xmlns. We have 2 choices:

 * using an XML catalog
 * develop that in Java with a plugin like the XMLPlugin

**Comment by angelozerr** [comment]
@ralfhandl I think you could be interested with this issue: Please give us feedback

**Comment by ralfhandl** [comment]
I'd definitely like to have automatic completion/validation of catalog files. Got validation of my catalog.xml working by starting it with

```xml
<?xml version="1.0"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <public publicId="urn:oasis:names:tc:entity:xmlns:xml:catalog" uri="./schemas/catalog.xsd" />
  <uri name="urn:oasis:names:tc:entity:xmlns:xml:catalog" uri="./schemas/catalog.xsd" />
```

Now vscode-xml knows how to validate catalog files 😄 

Would it be possible to have an "implicit" catalog with these entries that is packed into vscode-xml, together with the catalog XSD? I got http://xmlcatalogs.org/schema/1.1/catalog.xsd from http://xmlcatalogs.org/.

PS: I'm no expert on XML catalogs but it strikes me as odd that I always need two catalog entries for the same XML namespace:
* `<pubic />` to make code completion work,
* `<uri />` to make validation work

Should I open a separate issue for that`?

**Comment by angelozerr** [comment]
> Would it be possible to have an "implicit" catalog with these entries that is packed into vscode-xml, together with the catalog XSD

My work with https://github.com/angelozerr/lsp4xml/commit/84391cbe71975afbad90b4a1d6fac3ac2f98bfd2#diff-13747ce199e06fc38bd7e093a60e4a34R34 should call the  http://xmlcatalogs.org/schema/1.1/catalog.xsd from http://xmlcatalogs.org/ when "urn:oasis:names:tc:entity:xmlns:xml:catalog" is declared, it works great in my laptob, but we have test problem that I must fix it to enable it again.

But for the moment, if you wish to have completion and validation for catalog, you can declare your XMl Schema in your catalog and it should work.

> PS: I'm no expert on XML catalogs but it strikes me as odd that I always need two catalog entries for the same XML namespace:

Yes you hav ethis problem, please create an issue for that. I must debug Xerces to understand how it works (me too I don't know catalog).

**Comment by angelozerr** [comment]
Now https://github.com/angelozerr/lsp4xml/issues/215 was fixed, I have re-enabled XML Catalog plugin. If build tests passed, this issue should be fixed.

**Comment by angelozerr** [comment]
@ralfhandl build is passing, please retry this issue, thanks!

**Comment by ralfhandl** [comment]
@angelozerr not sure what was fixed/changed: validation and completion of "my" XML files (still) works with build #502.

Validation and completion of catalog files only works if the catalog contains the entry
```xml
  <public publicId="urn:oasis:names:tc:entity:xmlns:xml:catalog" uri="./schemas/catalog.xsd" />
```

Needing `<public>`  instead of (and in other cases in addition to) `<uri>` is still surprising, I have cross-checked with the XML Catalog specification and opened https://github.com/angelozerr/lsp4xml/issues/217 as a separate issue.

Thanks for the quick support!

**Comment by angelozerr** [comment]
Sorry @ralfhandl please reinstall it, now you should have compeltion and validation (based on XML Schema catalog) for :

```xml
<?xml version="1.0"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    //Should provide completion here
    <bad /> // error validation, because "bad" doesn't belong to the XML Schema catalog
</catalog> 
```

> validation and completion of "my" XML files (still) works with build #502.

Yes sure, but this issue os for your XML catalog file, not for XML files bound to the catalog.

> Needing <public> instead of (and in other cases in addition to) <uri> is still surprising, I have cross-checked with the XML Catalog specification and opened #217 as a separate issue.

Yes I know. I will study more #217

**Comment by angelozerr** [comment]
Here a demo:

![catalogcompletionandvalidation](https://user-images.githubusercontent.com/1932211/48353869-b3bd3200-e690-11e8-9e18-c60e5454a48b.gif)

**Comment by ralfhandl** [comment]
+1, works now with build #505

**Comment by fbricon** [comment]
@angelozerr are there any tests so we can close this one?

**Comment by angelozerr** [comment]
No I must write tests.
