### ISSUE TITLE
Support rootUri for XML catalog configuration

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#206]
When catalog path is relative:, 

```xml
{
    "xml.catalogs": [
        "./catalog.xml"
    ]
}
```

It is not loaded. It should use rootUri workspace.

**Comment by angelozerr** [comment]
This issue should be fixed. I must write a test yet.

**Comment by fbricon** [comment]
@angelozerr build is broken!

**Comment by angelozerr** [comment]
I cannot reproduce the problem wuth my Windows OS -(

**Comment by angelozerr** [comment]
@fbricon build is fixed but I have disable the fix of this issue. I don't understand why it doesn't work on Travis. In my case on Windows OS, all tests passed.

**Comment by fbricon** [comment]
ok thanks. Please use PRs until we complete the release.

**Comment by angelozerr** [comment]
> ok thanks. Please use PRs until we complete the release.

Yes sure! I was too confident. I promise you, I will wait for the release before pushing to master (or create a PR).

**Comment by angelozerr** [comment]
I have reactivated and test pass now.

**Comment by ralfhandl** [comment]
@angelozerr Thanks, works like a charm
