### ISSUE TITLE
Mark element coming from XML Schema/DTD for completion

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#210]
While studying bug with duplicate elements https://github.com/redhat-developer/vscode-xml/issues/78#issuecomment-437049479 I find it should be good to mark the completion elements origin (from XML Schema, from DTD, copy sibling)

A quick idea is to add -  XML Schema:

![image](https://user-images.githubusercontent.com/1932211/48245592-e09ceb00-e3eb-11e8-82ba-8c546162b890.png)

@fbricon @NikolasKomonen @ralfhandl what do you think about that?

**Comment by ralfhandl** [comment]
Will definitely reduce (my :smile:) confusion.

**Comment by ralfhandl** [comment]
On second thought: it would be even better if copy siblings that are also described in XML Schema or DTD are removed from the list, showing only one entry for equally named elements.

**Comment by angelozerr** [comment]
copy siblings should not done when XML is linked to a grammar. It works like this today when you define a xs:schemaLocation or xsi:noNamespaceShchemaLocation. In your case you have not that, because it uses XML Catalog. It's a bug that I must fix (XMLDocument#hasGrammar should test too grammar coming from XML Catalog). I must fix this bug.

**Comment by fbricon** [comment]
Would be even better if the name of the originating schema was used instead of the generic "XML Schema" label

**Comment by angelozerr** [comment]
@NikolasKomonen a quick idea that I had to display the XML Schema / DTD URI is to store the key in the content model document https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/model/ContentModelManager.java#L117 and after you can use it to display it in the CMLEementDeclaration. 

Don't hesitate to ping me if you need more information.
