### ISSUE TITLE
Don't add sibling element when completion items is filled with grammar

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#211]
In some case (I have just reproduce it once), there is duplicate element (element coming from sibling and element coming from grammar:

![image](https://user-images.githubusercontent.com/1932211/48260281-2f15ae00-e41b-11e8-8409-cdfb637638d4.png)

See https://github.com/angelozerr/lsp4xml/issues/210

This logic should work, but it fails in some case. I cannot reproduce it every time, but to be sure to avoid having this trouble, we must exectute completion of content model (from grammar) before sibling strategies and check we have NOT element coming from grammar to process sibling strategy.

**Comment by angelozerr** [comment]
@ralfhandl duplicate element should be fixed.

**Comment by ralfhandl** [comment]
+1: works!
