### ISSUE TITLE
Some managers like ContentModelManager, URIResolverManagerExtension should not be a singleton

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#215]
When I try to implement https://github.com/angelozerr/lsp4xml/issues/204 by adding a new simple URIResolver https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/catalog/XMLCatalogURIResolverExtension.java it breaks tests. It's so crazy:

 * when I launch the all tests, some tests failed.
 * when I launch only a test which has failed, it works?

After spending a lot of time, I see the problem is because each time test is executed, it updates singleton with some uriresolver, and we are not in the same context if we launch the all tests and just one test.

The problem is because URIResolverManagerExtension is a singleton, although it should be a singleton only for an instance of XMLLanguageService. 

This issue is for link an instance of URIResolverManagerExtension to an instance of XMLLanguageService to be in the same context (in test context) than real case 

I'm working on this issue.

**Comment by angelozerr** [comment]
This issue should be fixed. There were several JUnit tests which was wrong because they had some dependencies from a previous test (ex: a test which fill content model manager, and after the test used the filled content model manager).

Now we have clean tests.

**Comment by fbricon** [comment]
I've enabled runorder=random in the maven surefire plugin configuration, so we can better catch similar test failures. See https://github.com/angelozerr/lsp4xml/commit/2b80639cf95e2183ff75bf17759599322d00e5e9

**Comment by angelozerr** [comment]
> I've enabled runorder=random 

I didn't know that. Thank @fbricon !
