### ISSUE TITLE
Validation needs additional <uri> catalog entry

### ISSUE THREAD

**Issue by ralfhandl** [angelozerr/lsp4xml#217]
To make validation and completion work I currently need two catalog entries, e.g.
```xml
  <public publicId="urn:oasis:names:tc:entity:xmlns:xml:catalog" uri="./schemas/catalog.xsd" />
  <uri name="urn:oasis:names:tc:entity:xmlns:xml:catalog" uri="./schemas/catalog.xsd" />
```

From the [XML Catalog specification](https://www.oasis-open.org/committees/download.php/14809/xml-catalogs.html#s.ext.ent) I would have expected to just need the `<uri>` entry because `<public>` is intended for resolving *external identifiers* and expressly *not* for resolving XML namespace names:

> External Identifiers, as defined in [Production 75] of [XML], identify the external subset, entities, and notations of an XML document. They are not used to identify other resources such as namespace names, stylesheets, and schema languages other than DTDs; URI entries are used for that purpose.

However with just a `<uri>` entry neither validation nor code completion are triggered.

Note: this issue is of low importance as validation and completion work fine as long as the catalog contains these "duplicate" entries. Mentioning this in documentation on "how to write a catalog.xml" would be sufficient.

**Comment by angelozerr** [comment]
@ralfhandl I have tried to debug the xml-resolver project but to be honnest I'm a little lost -(

I have tried to use your XML catalog with Eclipse WTP, but only completion is working, the validation doesn't work. 

It should be really cool if somebody could help us to know if catalog is valid or not.

**Comment by ralfhandl** [comment]
@angelozerr Strange. I'm also using Eclipse Photon with the editor from 
* Eclipse XML Editors and Tools 
* 3.10.0.v201804210200	
* org.eclipse.wst.xml_ui.feature.feature.group	
* Eclipse Web Tools Platform

The file `...eclipse-workspace-Photon\.metadata\.plugins\org.eclipse.wst.xml.core\user_catalog.xml` only contains `<uri>` entries, e.g.
```xml
  <uri name="http://docs.oasis-open.org/odata/ns/edm" uri="platform:/resource/OData-TC/odata-csdl-schemas/schemas/edm.xsd"/>
  <uri name="http://docs.oasis-open.org/odata/ns/edmx" uri="platform:/resource/OData-TC/odata-csdl-schemas/schemas/edmx.xsd"/>
```

Validation and code completion both work fine with this catalog.

**Comment by angelozerr** [comment]
@ralfhandl once build will be finished, please retry it.

**Comment by fbricon** [comment]
@angelozerr I assume you'll add some tests ;-)

**Comment by angelozerr** [comment]
Yes sure @fbricon! It's a reason why I have not closed this issue and other issues of 0.0.3 like https://github.com/angelozerr/lsp4xml/issues/214

**Comment by ralfhandl** [comment]
@angelozerr works fine with build #506, thanks! My catalog.xml now only contains `<uri>` entries.

**Comment by angelozerr** [comment]
Great! is there some other issues with XML catalog?

**Comment by ralfhandl** [comment]
@angelozerr no issues with XML catalogs any more, thanks!

**Comment by angelozerr** [comment]
Test works, I close this issue. Thanks @again @ralfhandl !
