### ISSUE TITLE
Add warning when XML is not bound to a grammar

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#218]
When we try to bound a grammar to a XML file and this binding is not well confured (ex: XML file associations is not well configured, XML catalog not well configured) it's hard to see that.

A proposition si to mark XML root element as warning ("no grammar constraints") like WTP does:

![image](https://user-images.githubusercontent.com/1932211/48409184-6ea20a00-e73b-11e8-889c-f361de294f4d.png)

This warning should be a preference. @fbricon @NikolasKomonen what do you think about this idea?

**Comment by fbricon** [comment]
preference value should be an enum: {ignore, hint, info, warning, error}

I'd use hint by default, as I find it less intrusive. It doesn't generate a marker in the problems view in vscode, only in the open file.

**Comment by angelozerr** [comment]
Perfect!

**Comment by angelozerr** [comment]
@fbricon @NikolasKomonen I have implemented this feature. I must write test yet.

I have choosen `warnNoGrammar` as preference name https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/settings/ContentModelSettings.java#L26 but if you don't like it, please tell me, I will change it.

**Comment by fbricon** [comment]
can we call it "problems.noGrammar"? It'll allow us to handle similar messages in the future. And there's no severity implied in the name.

**Comment by angelozerr** [comment]
> can we call it "problems.noGrammar"? 

You mean having `ContentModelSettings#getProblems()#setNoGrammar(String noGrammar)` ?

**Comment by fbricon** [comment]
yes

**Comment by angelozerr** [comment]
Done @fbricon

**Comment by angelozerr** [comment]
@fbricon I reopen this issue because I must write tests.
