### ISSUE TITLE
DTD elements are not formatted

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#221]
Following up on #90, given:
```
<?xml version="1.0"?>
<!DOCTYPE note [
<!ELEMENT note (to,from,heading,body)>
    <!ELEMENT to (#PCDATA)>
        <!ELEMENT from (#PCDATA)>
                <!ELEMENT heading (#PCDATA)>
            <!ELEMENT body (#PCDATA)>
]>
<note>
    <from>Jani</from>
    <heading>Reminder</heading>
    <body>Don't forget me this weekend</body>
</note>
```

Formatting the document ignores the DOCTYPE content.

**Comment by angelozerr** [comment]
@NikolasKomonen to support DTD completion https://github.com/angelozerr/lsp4xml/issues/106 I need to  improve XMLParser to collect information of DocumentType (see https://en.wikipedia.org/wiki/Document_type_declaration)

The general syntax for a document type declaration is:

```
<!DOCTYPE root-element PUBLIC "FPI" ["URI"] [ 
<!-- internal subset declarations -->
]>
```
or

```
<!DOCTYPE root-element SYSTEM "URI" [ 
<!-- internal subset declarations -->
]>
```

We need not to work together about this parsing feature, so I tell me when you want to work on this format issue. I'm working on DTD completion, so I could start this parsing documenttype feature, but if you have started something, please tell me.

**Comment by angelozerr** [comment]
Thanks @NikolasKomonen!

**Comment by NikolasKomonen** [comment]
@angelozerr Just wanted to check if you needed this as soon as possible, or is it fine if I work on another issue first?

**Comment by angelozerr** [comment]
> @angelozerr Just wanted to check if you needed this as soon as possible, or is it fine if I work on another issue first?

I can manage with a uggly mean the extract of DTD system uri if you prefere working on another issues.

**Comment by NikolasKomonen** [comment]
@angelozerr Its fine, I'll be able to work on this now. The other issues are fixed now.

I just want to be sure, the parser should also cover this, eg: `<!ELEMENT foo (#PCDATA)>` for doctypes?

**Comment by angelozerr** [comment]
> I just want to be sure, the parser should also cover this, eg: <!ELEMENT foo (#PCDATA)> for doctypes?

For my issue with XML completion based on DTD, I don't need this feature. Me I need to get public, system uri. In otherwords, implement:

 * https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/dom/DocumentType.java#L114
 * https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/dom/DocumentType.java#L124

My first goal is to support external DTD. I will see after how to support internal DTD (DTD declared in the XML)

**Comment by angelozerr** [comment]
@NikolasKomonen I think you can work on this formatting issue now. Now you have 3 new structures:

 * DTDElementDecl for <!ELEMENT
 * DTDAttrList  for <!ATTRIBUTES
 * DOMEntity for <!ENTITY

That you can see in the outline. Now you can use it for format. Don't hesitate to update it to improve it according your need for format.

**Comment by NikolasKomonen** [comment]
@angelozerr Just wondering why you called it 'DOMEntity' and not 'DTDEntity' ?

**Comment by angelozerr** [comment]
> @angelozerr Just wondering why you called it 'DOMEntity' and not 'DTDEntity' ?

I have done this choice because DOMEntity implements org.w3c.dom.Entity. For the other structures ELEMENT and ATTLIST, it doesn't exists interfaces? I don't know why?

But if you prefer, we can rename it. @fbricon what do you think about that?

**Comment by fbricon** [comment]
if DOMEntity is meant to be used outside the context of DTD, then you can keep it. Else, if it's specific to DTD usage, renaming it is fine

**Comment by angelozerr** [comment]
I thinkit's for only DTD. Let's go to rename it.

**Comment by fbricon** [comment]
Formatting now breaks the document:
![broken-formatting](https://user-images.githubusercontent.com/148698/49331081-de9af780-f565-11e8-9fe5-f277e3cedd98.gif)
```xml
<!DOCTYPE features [
<!ELEMENT features (feature*)>
<!ELEMENT feature (#PCDATA)>
]>
<features>
	<feature>Validation</feature>
	<!-- this is 
	a comment 
	on multiple
	lines -->
	<feature>Highlighting</feature>
	<feature>Outline</feature>
					<feature>Formatting</feature>
					
	<feature>XSD support</feature>
	<feature>... and more</feature>
</features>
```
