### ISSUE TITLE
Provide a dedicated DTD Validator

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#223]
if you save http://java.sun.com/dtd/web-app_2_3.dtd locally and open it in VS Code, an error shows up on the 1st ELEMENT, L72. "The markup in the document preceding the root element must be well-formed."
DTDs do not follow the actual xml syntax but are part of the XML spec, so "The markup in the document preceding the root element must be well-formed." (and maybe other specific errors) should be ignored.
We still need tooling support for DTD (completion, validation ...)

**Comment by angelozerr** [comment]
@fbricon it shoud work better. Now you should have just DTD syntax error. It misses now adjust error range but to do that I'm waiting for the work of @NikolasKomonen about the improve of parser.

**Comment by angelozerr** [comment]
I close this issue since DTD validator was implemented. It misses tests and adjust error which will be done in https://github.com/angelozerr/lsp4xml/issues/225
