### ISSUE TITLE
Adjust range error for internal DTD declaration

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#225]
When internal DTD declaration is done with bad syntax, error is not well adjusted:

![image](https://user-images.githubusercontent.com/1932211/48502997-3684ef00-e841-11e8-9664-863e0e9b7cca.png)

To fix this issue we need that XMLDocument is able to parse DTD declaration (here <!Element). 

**UPDATE**  
  Implemented Error Codes:  

  [Refer here](https://github.com/apache/xerces2-j/blob/trunk/src/org/apache/xerces/impl/msg/XMLMessages.properties) for more info on each code.

- 	AttNameRequiredInAttDef,
- 	AttTypeRequiredInAttDef,
- 	AttlistDeclUnterminated,
- 	ElementDeclUnterminated,
- 	EntityDeclUnterminated,
- 	ExternalIDorPublicIDRequired,
- 	IDInvalidWithNamespaces,
- 	IDREFInvalidWithNamespaces,
- 	IDREFSInvalid,
- 	LessthanInAttValue,
- 	MSG_ATTRIBUTE_NOT_DECLARED,
- 	MSG_ATTRIBUTE_VALUE_NOT_IN_LIST,
- 	MSG_CONTENT_INCOMPLETE,
- 	MSG_CONTENT_INVALID,
- 	MSG_ELEMENT_NOT_DECLARED,
- 	MSG_ELEMENT_TYPE_REQUIRED_IN_ATTLISTDECL,
- 	MSG_ELEMENT_TYPE_REQUIRED_IN_ELEMENTDECL,
- 	MSG_ELEMENT_WITH_ID_REQUIRED,
- 	MSG_ENTITY_NAME_REQUIRED_IN_ENTITYDECL,
- 	MSG_FIXED_ATTVALUE_INVALID,
- 	MSG_MARKUP_NOT_RECOGNIZED_IN_DTD,
- 	MSG_NOTATION_NAME_REQUIRED_IN_NOTATIONDECL,
- 	MSG_OPEN_PAREN_OR_ELEMENT_TYPE_REQUIRED_IN_CHILDREN,
- 	MSG_REQUIRED_ATTRIBUTE_NOT_SPECIFIED,
- 	MSG_SPACE_REQUIRED_AFTER_NOTATION_NAME_IN_NOTATIONDECL,
- 	NotationDeclUnterminated,
- 	OpenQuoteExpected,
- 	OpenQuoteMissingInDecl,
- 	QuoteRequiredInPublicID,
- 	QuoteRequiredInSystemID
- 	SpaceRequiredAfterSYSTEM,

**Comment by fbricon** [comment]
@angelozerr what's the status on this one?

**Comment by angelozerr** [comment]
It starts working with <!ELEMENT which is broken. I need to support <!ATTRLIST and <!ENTITY broke. 

But I think I will miss some errors again. My proposition is to support broke of <!ATTRLIST and <!ENTITY and close it. We will open a new issue if we will find another error not supported.

**Comment by fbricon** [comment]
Given this snippet:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Folks [
	<!ELEMENT Folks (Person*)>
	<!ELEMENT Person (Name,Email?)>
	<!ATTLIST Person Pin ID #REQUIRED>
	<!ATTLIST Person Friend IDREF #IMPLIED>
	<!ATTLIST Person Likes IDREFS #IMPLIED>
	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Email (#PCDATA)>
	]>
<Folks>
	<Person Pin="id1">
        <Name>Fred</Name>
        <Email>frfr</Email>
    </Person>
    <Person Pin="id2" Friend="" Likes="id1">
        <Name>Bob</Name>
    </Person>
</Folks>
```
The diagnostic on `Likes` has the wrong range:
<img width="874" alt="screen shot 2018-12-05 at 2 32 18 pm" src="https://user-images.githubusercontent.com/148698/49538970-98fa6980-f89a-11e8-8652-81b2e8aaeccc.png">

> Attribute value "" of type IDREF must be an NCName when namespaces are enabled.

**Comment by fbricon** [comment]
Same snippet, but with some random value in `Friend`:
<img width="799" alt="screen shot 2018-12-05 at 2 34 19 pm" src="https://user-images.githubusercontent.com/148698/49539113-f393c580-f89a-11e8-9379-bfb7d1442d61.png">
```json
{
	"resource": "/Users/fbricon/Downloads/sample-resources/some.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "MSG_ELEMENT_WITH_ID_REQUIRED",
	"severity": 8,
	"message": "An element with the identifier \"vfg\" must appear in the document.",
	"source": "xml",
	"startLineNumber": 19,
	"startColumn": 9,
	"endLineNumber": 19,
	"endColumn": 9
}
```

**Comment by fbricon** [comment]
Wrong attribute, underlines next attribute:
<img width="761" alt="screen shot 2018-12-05 at 2 37 13 pm" src="https://user-images.githubusercontent.com/148698/49539291-4f5e4e80-f89b-11e8-9b73-c01154c35322.png">

```json
{
	"resource": "/Users/fbricon/Downloads/sample-resources/some.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "MSG_ATTRIBUTE_NOT_DECLARED",
	"severity": 8,
	"message": "Attribute \"Frien\" must be declared for element type \"Person\".",
	"source": "xml",
	"startLineNumber": 16,
	"startColumn": 32,
	"endLineNumber": 16,
	"endColumn": 37
}
```

**Comment by fbricon** [comment]
Unknown doctype node type:
<img width="1052" alt="screen shot 2018-12-05 at 2 39 44 pm" src="https://user-images.githubusercontent.com/148698/49539493-c4318880-f89b-11e8-84b7-ee002220ad8c.png">


<img width="1052" alt="screen shot 2018-12-05 at 2 39 44 pm" src="https://user-images.githubusercontent.com/148698/49539470-b845c680-f89b-11e8-8008-9b503493004f.png">

**Comment by NikolasKomonen** [comment]
All above issues are addressed

**Comment by fbricon** [comment]
wrong ranges for 
- MSG_ELEMENT_ALREADY_DECLARED (duplicate `<!ELEMENT Email (#PCDATA)>` )
- wrong range for PEReferenceWithinMarkup, see:
```xml
<!DOCTYPE Folks [
  <!ENTITY % Folks "(%bar;)*">
]>
```
