### ISSUE TITLE
Deploy lsp4xml to a public Maven repository

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#229]
Deploy to either Sonatype's [OSSRH](https://central.sonatype.org/pages/ossrh-guide.html) or [bintray](https://blog.bintray.com/2015/09/17/publishing-your-maven-project-to-bintray/).

Eventually it'd be ideal to have the jars available on Maven Central, but I'd wait for the project to be contributed to the Eclipse Foundation before we do that, as we're using the eclipse.org namespace.

From my experience, deploying to bintray is pretty easy, as it doesn't require JFrog to enable anything specific to your project. I never tried OSSRH, but I know it's more complicated.

**Comment by dhuebner** [comment]
@fbricon Are you guys also plan to publish the `org.eclipse.lsp4xml-all.jar`   uber jar?

**Comment by fbricon** [comment]
yes. I'll probably start manually pushing bits to bintray initially, as it's the simplest.

**Comment by dhuebner** [comment]
@fbricon True... 
An another question. What LSP4J version will be included? I saw you are using a 0.5.0 beta, maybe it would make sense to switch to the current 0.6.0 release?

**Comment by fbricon** [comment]
@dhuebner please open a ticket for the lsp4j update

**Comment by dhuebner** [comment]
Done: https://github.com/angelozerr/lsp4xml/issues/254

**Comment by fbricon** [comment]
So right now, snapshot builds are deployed to https://oss.jfrog.org/webapp/#/artifacts/browse/tree/General/oss-snapshot-local/org/lsp4xml/org.eclipse.lsp4xml
Add this repository to your pom.xml or settings.xml:
```xml
<repository>
  <id>oss-jfrog-snapshots</id>
  <url>https://oss.jfrog.org/artifactory/libs-snapshot</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
```

Here are the Maven coordinates:
```xml
<dependency>
    <groupId>org.lsp4xml</groupId>
    <artifactId>org.eclipse.lsp4xml</artifactId>
    <version>0.0.3-SNAPSHOT</version>
    <!-- classifier:all includes all dependencies -->
    <classifier>all</classifier>
</dependency>
```

for Gradle:
```
compile(group: 'org.lsp4xml', name: 'org.eclipse.lsp4xml', version: '0.0.3-SNAPSHOT', classifier: 'all')
```

@angelozerr I'd like to rename the `all` jar to something else, because it seems to imply it includes all the extensions as well, which it does not. 
`jar-with-dependencies` is the default name for the kind of jar we ship, but we could use anything else: `fat`, `include-dependencies`, `with-dependencies` ... WDYT?

**Comment by fbricon** [comment]
I like `uber` ;-)

**Comment by NikolasKomonen** [comment]
I'm fine with whatever :)

**Comment by fbricon** [comment]
So I went with `uber` as a suffix, make sure to adapt your launching scripts!!! 
Update on the Maven coordinates:
```xml
<dependency>
    <groupId>org.lsp4xml</groupId>
    <artifactId>org.eclipse.lsp4xml</artifactId>
    <version>0.3.0-SNAPSHOT</version>
    <!-- classifier:uber includes all dependencies -->
    <classifier>uber</classifier>
</dependency>
```

for Gradle:
```
compile(group: 'org.lsp4xml', name: 'org.eclipse.lsp4xml', version: '0.0.3-SNAPSHOT', classifier: 'uber')
```
