### ISSUE TITLE
Completion for DTD <!ELEMENT, <!ATTRIBUTE, 

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#232]
Support for completion 

 * for DTD elements 

`<! <- Ctrl+Space shows <!ELEMENTS <!ATTRIBUTE, <!ENTITY`

**Comment by angelozerr** [comment]
@fbricon it's basic but it starts working:
![dtdcompletion](https://user-images.githubusercontent.com/1932211/49305784-86fe7c80-f4d0-11e8-86a9-ad2e1e870dc5.gif)

**Comment by fbricon** [comment]
If I type `<`, select "internal entity", autocompletion inserts `<!ENTITY entity-name "entity-value" >`, so I end up with 2 opening brackets.
Also the placeholders order is wrong. the value is selected first, it should be the entity name
