### ISSUE TITLE
Autoclose self-closing tags

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#239]
As an improvement to tag autoclosing, if we type `<foo /`, the closing `>` should be added automatically (controlled by a new preference, `autoCloseTags.selfClosingTags.enabled`)

**Comment by angelozerr** [comment]
It should be cool if this option could manage too the same feature than WTP:

![foo](https://user-images.githubusercontent.com/1932211/49278475-30b81c00-f485-11e8-8418-4bb22cb24569.gif)

**Comment by fbricon** [comment]
Yes that's pretty cool. Need to make sure it only works if tag is empty
