### ISSUE TITLE
Return hover as Markdown

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#245]
Currently, hover returns documentation as text, meaning if the content is actual html, then the client doesn't render it in a user-friendly way. See a hover over the `<packaging>` element of a pom.xml:

<img width="560" alt="screen shot 2018-12-02 at 1 13 02 pm" src="https://user-images.githubusercontent.com/148698/49343276-3acc4d00-f634-11e8-9d11-5bbd2d3317a9.png">

We could probably transform the html doc into markdown, using the [remark](https://github.com/kotcrab/remark-java/) library, like in [jdt.ls](https://github.com/eclipse/eclipse.jdt.ls/blob/fc6b40e58808d23a324628a1e79e50f117c534de/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/javadoc/JavaDoc2MarkdownConverter.java). That'd also add jsoup as a dependency of the project.

**Comment by fbricon** [comment]
For now, the main issue I have with this approach is, escaped xml is swallowed during the markdown conversion. e.g for https://github.com/felixfbecker/PowerShellXSD/blob/master/Test.Types.ps1xml:

<img width="948" alt="screen shot 2019-01-24 at 9 22 27 am" src="https://user-images.githubusercontent.com/148698/51684294-be157980-1fb9-11e9-9104-86b8711f620f.png">

**Comment by angelozerr** [comment]
> We could probably transform the html doc into markdown, using the remark library, like in jdt.ls. That'd also add jsoup as a dependency of the project.

Could we not create our own (very simply) markdown parser for that:

 * we will avoid having 2 new dependencies which will grow up the size of xml language server JAR
 * we will manage the markdown parser for our need like "For now, the main issue I have with this approach is, escaped xml is swallowed during the markdown conversion. "

**Comment by angelozerr** [comment]
Fred i'm sorry to insist but i think we could use our xmlscanner to parse documentation and generate markdown. I think its not an hard task. No?

**Comment by fbricon** [comment]
From a technical perspective, it would probably be better/more efficient to reuse the xmlscanner. But I'm not sure how much work it will be to rewrite a complete markdown converter, I'm not sure it'll be as easy as you think. But feel free to explore that option
