### ISSUE TITLE
textDocument/documentSymbol should return DocumentSymbols if the client supports it

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#253]
DocumentSymbol is the [only way](https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#document-symbols-request-leftwards_arrow_with_hook) to accurately represent a tree structure.

**Comment by fbricon** [comment]
kinda relates to #226

**Comment by angelozerr** [comment]
@fbricon now DTD !ATTLIST should be appear as children of !ELEMENT:

![image](https://user-images.githubusercontent.com/1932211/49666762-5763ed00-fa59-11e8-98ca-636ebe3676bd.png)

Thanks a lot for having suggested me to support DocumentSymbol!

Needs writing test now.

**Comment by angelozerr** [comment]
Test wad one, I close this issue.
