### ISSUE TITLE
Sanitize the copyright headers

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#256]
we currently have a mix of EPL-1.0, EPL-2.0, no headers (maybe others) in the codebase. The project is advertised as EPL-2.0, so everything should be aligned.
We prolly need to add some checks to the Maven build that'll enforce proper copyright header policy.

**Comment by angelozerr** [comment]
@fbricon could you do that? If yes, please tell me when you wish to do that because I need to push my work.

**Comment by fbricon** [comment]
I'll look into it later. You can push your work for now

**Comment by angelozerr** [comment]
Ok @fbricon. Please ping me when you wish to do that.
