### ISSUE TITLE
Use root element for XMLClientSettings

### ISSUE THREAD

**Issue by dhuebner** [angelozerr/lsp4xml#257]
I'm about to add support for the lsp4xml in theia. In theia, when sending settings to a server, one or more roots can be selected (in my case it's `xml`). Doing so, all the `xml.*` setting will be send to the server wrapped by the root object.

```
"xml": {
     "logs":{"client":true},
     "format":{"enabled":true,"spaceBeforeEmptyCloseTag":true},
     "trace":{"server":"off"}
    }
```

The idea behind that is that the server may later rely on other client settings e.g. `http` to get the `proxy` settings, than you would just add a new `xml` sibling `http`

Would it be possible to load the setting with a `xml` prefix?
Does it make sense?

**Comment by dhuebner** [comment]
Related code in the vscode extension:

https://github.com/redhat-developer/vscode-xml/blob/d198be337e588f8217c3e9108cab21b3d74912e8/src/extension.ts#L95

**Comment by angelozerr** [comment]
@fbricon what do you think about that?

**Comment by fbricon** [comment]
@angelozerr I'm fine with that. That was actually what I expected from the server initially.
