### ISSUE TITLE
Add preference to enable/disable validation

### ISSUE THREAD

**Issue by dhuebner** [angelozerr/lsp4xml#260]
It would be nice to have a possibility to disable XML validation

**Comment by fbricon** [comment]
You mean schema validation or also want to skip well-formedness checks?

**Comment by dhuebner** [comment]
@fbricon The best would be to have both. At the moment, the most important is schema validation

**Comment by angelozerr** [comment]
@dhuebner I'm aware to add an `enableValidation` preferences, but before I would like to understand why you need that?

**Comment by dhuebner** [comment]
@angelozerr Just my experience :) 
There could be false positives or bugs in validation or you just expect a malformed xml (test cases).  
E.g. if I run xml validator in eclipse for the org.eclipse.lsp4xml project it reports me over 120k errors 

<img width="647" alt="bildschirmfoto 2018-12-07 um 11 02 31" src="https://user-images.githubusercontent.com/454322/49641183-bc92f080-fa0f-11e8-8870-8b5fa766f81f.png">
