### ISSUE TITLE
Formatting document with unclosed closing tag moves said tag down

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#269]
formatting this:
```xml
<?xml version="1.0"?>
<note>
	<to>Fred</to
	<from>Jani</from>
		<heading>Reminder</heading>
			<body>Don't forget me this weekend</body>
</note>
```

yields:
```xml
<?xml version="1.0"?>
<note>
	<to>Fred<from>Jani</from>
		<heading>Reminder</heading>
		<body>Don't forget me this weekend</body>
	</to
</note>
``` 

The tag `</to` was moved down to enclose everything

**Comment by fbricon** [comment]
this happens with master.

In the previous release, this would just remove the unclosed closing tag:
```xml
<?xml version="1.0"?>
<note>
	<to>Fred<from>Jani</from>
		<heading>Reminder</heading>
		<body>Don't forget me this weekend</body>
</note>
```

**Comment by fbricon** [comment]
I reverted the commit as it totally breaks dtd outline

**Comment by NikolasKomonen** [comment]
@fbricon Do you have an example of what breaks it?

**Comment by fbricon** [comment]
No outline is returned at all

**Comment by NikolasKomonen** [comment]
![selection_012](https://user-images.githubusercontent.com/32624665/50292710-d08f1700-043f-11e9-8901-4a03916152c1.png)
@fbricon is yours not getting something like this?
