### ISSUE TITLE
Compatibility with OSGi and p2

### ISSUE THREAD

**Issue by mickaelistria** [angelozerr/lsp4xml#288]
As we're integrating XML-LS in Eclipse IDE, it would be nice if the jar declared dependencies in the OSGi format as well (with a MANIFEST.MF). With this, then we'll more easily move away from the farjar which contains a lot of libraries we already have loaded in the application and can reuse.

**Comment by fbricon** [comment]
I'm fine with that. Feel free to provide a quality patch ;-)

**Comment by mickaelistria** [comment]
> Feel free to provide a quality patch ;-)
>

:D
We'll try, but probably a matter of several weeks before it becomes high
enough priority.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, for Red Hat Developers <https://developers.redhat.com/>

**Comment by mickaelistria** [comment]
I think we can just add http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#adding-osgi-metadata-to-existing-projects-without-changing-the-packaging-type and adding a tycho-ecliserun mojo invocation to call p2 publisher in the pom.xml should do the trick.

**Comment by mickaelistria** [comment]
Submitted PR https://github.com/angelozerr/lsp4xml/pull/301 implementing what I mentioned in previous comment, this combined with https://www.jfrog.com/confluence/display/RTF/P2+Repositories would give total satisfaction.

**Comment by mickaelistria** [comment]
Thanks for merging the patch @fbricon . Could you please publish a build with the profile enabled and configure Artifactory so the p2 repo gets easily accessible: https://www.jfrog.com/confluence/display/RTF/P2+Repositories ?

**Comment by mickaelistria** [comment]
Is there any progress on this topic? Did you manage to push a p2 repo to artifactory?

**Comment by fbricon** [comment]
I got an artifactory-pro account from JFrog, now need to setup everything. Hopefully will be able to do that this week

**Comment by mickaelistria** [comment]
Eclipse Simrel 2019-03 freezes in 11 days. So unless you can do it very soon, let's not rush and let's delay that for after the 15th.

**Comment by fbricon** [comment]
Snapshots deployed to https://lsp4xml.jfrog.io/lsp4xml/generic-local/p2/lsp4xml/0.4.0-SNAPSHOT/
Will comment about the release URL once 0.4.0 is out

**Comment by mickaelistria** [comment]
Thanks a lot!
