### ISSUE TITLE
XMLScanner Tests

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#29]

**Comment by NikolasKomonen** [comment]
Working on it.

**Comment by angelozerr** [comment]
Very cool! My idea was to similar test than https://github.com/Microsoft/vscode-html-languageservice/blob/master/src/test/scanner.test.ts

**Comment by NikolasKomonen** [comment]
Great, my implementation is similar to this. I'll look into what seems best and use these cases. Thanks.

**Comment by angelozerr** [comment]
That's cool. @NikolasKomonen please add (see #29) in your commit to reference this issue.
