### ISSUE TITLE
Fix error range for `cvc-datatype-valid-1-2-1`

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#323]
If only integers are allowed as content and you have:

```xml
<a xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
   xsi:noNamespaceSchemaLocation="intType.xsd">

  TEXT
  

</a>
```

with XSD:

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="a" type="xs:integer">
  </xs:element>
</xs:schema>
```

The highlight could be cleaned up to the first and last character of text here:
![Selection_050](https://user-images.githubusercontent.com/32624665/59116471-a1029700-8919-11e9-83b1-6c2885ff1710.png)

And in the case a user puts in a tag the highlight, error message should be adjusted to include the first tag it comes across:
![Selection_051](https://user-images.githubusercontent.com/32624665/59116556-d14a3580-8919-11e9-914b-6c9eaa5e39ef.png)

**Comment by angelozerr** [comment]
@NikolasKomonen could you please add a simple xml schema and simple xml in this issue to reproduce quickly your issue. It will help too when tests will be written. Thanks!

**Comment by xorye** [comment]
@angelozerr working on this now

**Comment by xorye** [comment]
@angelozerr @NikolasKomonen If there is only whitespace and newlines, is it okay if the error range looks like this?

![image.png](https://images.zenhubusercontent.com/5ce7f5b6e541a05e6eab3af1/6483df72-bcbd-41d8-9b51-1d98916980b1)

**Comment by xorye** [comment]
Any opinions on this case? This case is when there is whitespace in the middle of text.

![image.png](https://images.zenhubusercontent.com/5ce7f5b6e541a05e6eab3af1/ae4d9f3f-c223-43cc-8bd9-7d13cd686ade)

**Comment by fbricon** [comment]
compare with eclipse/idea

**Comment by xorye** [comment]
Eclipse looks like this:
![image](https://user-images.githubusercontent.com/20326645/61727763-e3edc200-ad41-11e9-8851-6c51d30882ab.png)
Which is what we have already, except that eclipse ignores the newline character.

IntelliJ looks like this:
![image](https://user-images.githubusercontent.com/20326645/61727546-8e191a00-ad41-11e9-8807-543619d33654.png)
IntelliJ only underlines the parent element.

The IntelliJ way is definitely easier to implement but it's not what was initially desired. 

Referring back to the two screenshots I posted yesterday, should I just keep them as is, for now?

**Comment by fbricon** [comment]
yeah keep as-is
