### ISSUE TITLE
Launch instructions

### ISSUE THREAD

**Issue by AmjadHD** [angelozerr/lsp4xml#376]
I'm trying to use a snapshot from https://lsp4xml.jfrog.io/lsp4xml/generic-local/p2/lsp4xml/
but I don't know how to launch as I have little to no knowledge of Java, can you provide me with instructions to run the server ? Thanks.

**Comment by NikolasKomonen** [comment]
@AmjadHD 

Hi, what IDE do you plan to use it on?

This repo (lsp4xml) is the server side of the client/server relation.

Client side implementations that will get the server up and running for you already exist.

If you plan to use VSCode, you can install the extension here: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml

**Comment by AmjadHD** [comment]
actually, i want to run it with sublime text via it's [LSP](https://packagecontrol.io/packages/LSP), I downloaded the 0.5.1 snapshot jar file, i don't know how to launch it.

**Comment by fbricon** [comment]
You can look at how the server is launched from the vscode-xml extension: https://github.com/redhat-developer/vscode-xml/blob/master/src/javaServerStarter.ts#L23

**Comment by AmjadHD** [comment]
Isn't a language server supposed to have an interface (e.g a shell script) to launch it and connect it to a an arbitrary client, this seems rather specific to vscode.

**Comment by NikolasKomonen** [comment]
A language server should just be responsible for receiving a request in the json format that follows the LSP, and then replying with the correct response.

There is some required preparation to actually hook up the language server to the IDE.

For example in VSCode we need the client side to be setup to handle things such as:

  1) Telling the client that our XML language server can handle LSP request related to XML files:
       https://github.com/redhat-developer/vscode-xml/blob/master/src/extension.ts#L54

  2) Telling the client what available preferences/settings the server can handle:
       https://github.com/redhat-developer/vscode-xml/blob/master/package.json#L65

  3) How to actually start up the language server (some parameters need to be set)
      https://github.com/redhat-developer/vscode-xml/blob/master/src/javaServerStarter.ts#L12

**Comment by AmjadHD** [comment]
I finally succeded to make it work in sublime text with:
```sh
java -DwatchParentProcess=false -noverify -Xmx64M -XX:+UseG1GC -XX:+UseStringDeduplication -jar PATH/TO/org.eclipse.lsp4xml-uber.jar
```
I couldn't build it, so I had to use the one in the vscode extension, but it's working fine, thanks for the help 🙂.

**Comment by NikolasKomonen** [comment]
@AmjadHD did you have to make a configuration file to connect it to sublime text?

If there were steps to set it up could you put it here, this will be useful for others who might want
to use the XML ls on sublime.

**Comment by AmjadHD** [comment]
- LSP settings file: https://github.com/tomv564/LSP/blob/master/LSP.sublime-settings
- XML server configurations: https://github.com/tomv564/LSP/issues/578#issuecomment-495951811, these should be added to `clients` in the user version of the LSP settings file.
- LSP documentation: https://lsp.readthedocs.io/en/latest/

**Comment by NikolasKomonen** [comment]
@AmjadHD thanks for the info!
