### ISSUE TITLE
How to launch the server and establish a connection to it via client?

### ISSUE THREAD

**Issue by lepantella** [angelozerr/lsp4xml#377]
I'm trying to implement a browser text editor (Monaco editor through angular 7) with LSP for XML. I cloned lsp4xml and built org.eclipse.lsp4xml-0.3.0-uber.jar. Now what I don't understand about it is how does it work and what ports does it occupy. My understanding is that if you have a server of some kind, your need a URL of some sort (ex. https://localhost:3000/) and with client you connect to that server. Also whenever I do `java -jar org.eclipse.lsp4xml-0.3.0-uber.jar` I get no console output, not even that the server is up and running. In numerous tutorials I found online, people have client and server in one application and the server is usually written inside, not exported as a .jar. It would be great if you could expand the documentation on github page, since the LSP is still a very new thing to programming world. Thanks!

**Comment by lepantella** [comment]
Also it's good to mention that I did `netstat -a -b` on windows 10 machine while the server was running and no ports were occupied by the server. I also searched through the source code for "5008", but got no results in terms of the "default" port for the server.

**Comment by angelozerr** [comment]
The default connection type in lsp4xml is stdio. It exists too ipc (I'm not sure it's supported) and sockets. Never played with it, but please read https://github.com/angelozerr/lsp4xml#developer

The lsp4xml doesn't provide an http server like you need, but I'm not confortable with this topic, perhaps @fbricon  could give us more info.

**Comment by angelozerr** [comment]
I close this issue in favor to https://github.com/angelozerr/lsp4xml/issues/376
