### ISSUE TITLE
Documents with an Internal Subset DOCTYPE shouldn't stop trying to bind

### ISSUE THREAD

**Issue by zwaldowski** [angelozerr/lsp4xml#379]
My organization has documents like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
    <!ENTITY foo "Bar">
]>
```

I'm trying to bind these documents using `fileAssociations`, but lsp4xml stops trying to bind at the `DOCTYPE`. It should continue looking for `xsi:schemaLocation` and in `fileAssociations` when the `DOCTYPE` lacks a DTD reference.

**Comment by angelozerr** [comment]
@zwaldowski could you please share a little vscode project with cases that you are describing please and give us trouble that you have (completion that you are waiting). Thanks!

**Comment by zwaldowski** [comment]
See [here](https://gist.github.com/zwaldowski/96c49e4c9e9f7893c370ccda37e93ca8). See the screenshots in the gist's comments.

I was having trouble getting the `fileAssociations` to bind correctly, so it's not a full vscode project; that's not the issue, though (that's my own inexperience 🙂). So it's just the single `article.xml` demonstrating the issue.

**Comment by angelozerr** [comment]
Thank's @zwaldowski for your feedback. I tested with your article.xml and I have the same issue but WTP XML Editor from Eclipse display the same errors. I'm not sure that we can mix internal DTD and XML Schema like this?

**Comment by zwaldowski** [comment]
I'm not familiar with WTP XML Editor. When we use Jing to render these documents, we bind a RelaxNG schema to it and it handles the entities fine. We've done this for ~15 years. Can you help me understand why this shouldn't work another way, perhaps?

**Comment by angelozerr** [comment]
It's a limitation of Xerces. But I found a topic about this problem https://www.oxygenxml.com/forum/topic12812.html#p36904 and Oxygen fixes the problem. The idea is to not validate XML with DTD (DOCTYPE) if DOCTYPE doesn't define <!ELEMENT or doesn't define PUBLIC, SYSTEM path.

I will try to follow this rule. I give you feedback if I can manage that.

**Comment by zwaldowski** [comment]
Amazing work, thanks!

**Comment by angelozerr** [comment]
Glad it works for you @zwaldowski .Many thanks for your feedback.
