### ISSUE TITLE
.ent and .mod files should be parsed as DTDs

### ISSUE THREAD

**Issue by zwaldowski** [angelozerr/lsp4xml#380]
DTDs frequently modularize long lists of entities using external files with the `.ent` extension. These should get syntax-checked as DTDs as well.

Technically, any extension can be used for this purpose; I've also seen `.mod`.

**Comment by angelozerr** [comment]
Perhaps lsp4xml should provide a preference for thoses DTD file extensions?

**Comment by angelozerr** [comment]
> Technically, any extension can be used for this purpose; I've also seen .mod.

Yes sure but it's a little hard to do that because there are synatx coloration to manage in vscode, etc. After reading some documentation, it seems there are 3 extensions (as you said):

 * dtd
 * mod
 * ent

We need to support those extension

**Comment by angelozerr** [comment]
For syntax coloration, we need wait for accept of my PR for vscode https://github.com/microsoft/vscode/pull/77496
