### ISSUE TITLE
Completion in svg file proposes many duplicates

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#386]
Editing an svg file like this one causes completion to return many duplicate items:
```xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg">
    <animate attributeName="foo">
        <
    </animate>
</svg>

```

<img width="929" alt="Screen Shot 2019-05-22 at 6 41 07 PM" src="https://user-images.githubusercontent.com/148698/58213751-48988c00-7cc1-11e9-8112-c3539621bcdd.png">

Referenced from: https://github.com/redhat-developer/vscode-xml/issues/141

**Comment by angelozerr** [comment]
@xorye please see my PR at https://github.com/angelozerr/lsp4xml/pull/391 which fixes this issue. Ignore it if you wish and create a new PR.

**Comment by fbricon** [comment]
Proposed solution fixes the duplicate entries issue.
Dunno if it's related or not, but initial completion request is usually not working. It takes several tries before I get completion results after restarting the server. Something's fishy here.
