### ISSUE TITLE
End Extension on Timeout

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#40]
Create a way to end the server extension process if the IDE stops responding.

**Comment by angelozerr** [comment]
What is your suggestion?

**Comment by NikolasKomonen** [comment]
I was talking with Fred, he suggested a timeout after the server stops receiving responses from the client. It will be similar to JDT LS and how they do it.

**Comment by angelozerr** [comment]
If I rememeber I have done that, but I will follow your PR.

**Comment by fbricon** [comment]
@angelozerr currently the server only forces System.exit after calling the `exit` command. If the client died before that, or for whatever other reason, the server might still be alive indefinitely after the client is gone. 
The idea here is to check if the parent PID is still running after the server is idle for more than a given time. If it's not, then the serve will commit seppuku in an honorable way :-)
See https://github.com/eclipse/eclipse.jdt.ls/blob/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/ParentProcessWatcher.java

**Comment by angelozerr** [comment]
Thanks @fbricon for the clarification!

**Comment by angelozerr** [comment]
@fbricon @nNikolasKomonen I have tried to implement your issue in https://github.com/angelozerr/lsp4xml/commit/05496c3a62689b5d4f1746e48bb36845c838c781 Please tell me if it's OK and close the issue in this case. Thanks!

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/lsp4xml/commit/05496c3a62689b5d4f1746e48bb36845c838c781 and https://github.com/angelozerr/lsp4xml/pull/83
