### ISSUE TITLE
Fix error range for `cos-all-limited.2`

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#407]
![image](https://user-images.githubusercontent.com/32624665/58705110-30d59d80-837c-11e9-84d4-dce58da1aede.png)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="testType">
		<xs:all>
			<xs:element name="testEle" minOccurs="2" maxOccurs="unbounded" type="xs:string"/>
		</xs:all>
	</xs:complexType>
</xs:schema>
```

**Comment by xorye** [comment]
@NikolasKomonen  should the error range cover "xs:all" ?

**Comment by xorye** [comment]
> @NikolasKomonen should the error range cover "xs:all" ?

I got confirmation that it should.

**Comment by fbricon** [comment]
Feels like xs:element should be underlined unstead, or even better the "unbounded" value.
