### ISSUE TITLE
Emmet Extension

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#41]
It should be cool if we could have Emmet support by providing a new  Emmet Extension like it exists for teh vscode html language server:

![emmetdemo](https://user-images.githubusercontent.com/1932211/43709270-a8ddef80-996c-11e8-8d43-f54293bc1768.gif)

Guys, it's just an idea, please vote if you like it. Thanks!

**Comment by apupier** [comment]
just take care that nashorn has been deprecated and is planned to be removed from the JVM, see http://openjdk.java.net/jeps/335

**Comment by angelozerr** [comment]
Thanks @apupier for the info! I was aware of that -( I had in mind to manage several JS engine (Nashorn, Rhino, Node.js etc) but we will that in the future.

**Comment by angelozerr** [comment]
> While I like the idea of providing emmet support, the reliance on a Javascript engine makes me cringe a little. 

Sad I don't like the idea -( My first idea was to translate the emmet expand/extract abbreviation in Java, but I have gave up the idea because it's a long task and we will not benefit from the fix/improve of emmet work.

> Good thing it's done in its own extension though.

It was one reason why I wanted to do extension:)
