### ISSUE TITLE
Fix Error Range for `src-element.3`

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#420]
Given:
```xml
<a xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
     xsi:noNamespaceSchemaLocation="intType.xsd">
	<b></b>
</a>
```

and the XSD:
```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="a" type="xs:integer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="b"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

You get errors on both documents:

The XML:
![Selection_048](https://user-images.githubusercontent.com/32624665/59116202-03a76300-8919-11e9-8c32-c7ca3c9a97bf.png)

The XSD:
![Selection_047](https://user-images.githubusercontent.com/32624665/59116168-f0949300-8918-11e9-8808-bb3db6bd128a.png)

**Comment by xorye** [comment]
For the XML, I was thinking the error range should cover the element name "a".

For the XSD, should the error range be at "xs:element"? 
Or should it be at "type="xs:integer"" or "xs:complexType"?

**Comment by xorye** [comment]
This is what I currently have

xml:
![image](https://user-images.githubusercontent.com/20326645/59384312-e961f080-8d2f-11e9-9d48-36bebe9883ea.png)


xsd:
![image](https://user-images.githubusercontent.com/20326645/59384282-d9e2a780-8d2f-11e9-8d60-b4ef3cf25bc7.png)
