### ISSUE TITLE
Improve closeTag to refactor to self close tag

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#422]
One feature that I like in WTP XML Editor is the refactor to self close tag. Here a demo:

![AutoTagClose](https://user-images.githubusercontent.com/1932211/59142543-217bd300-89c0-11e9-86c1-9d0f13b57ddc.gif)

**Comment by fbricon** [comment]
Already fixed as part of #239

![Jun-08-2019 08-10-02](https://user-images.githubusercontent.com/148698/59147105-6b1aec80-89c5-11e9-8224-fc95715a0779.gif)

**Comment by angelozerr** [comment]
I don't remember that, it's excellent! Sorry for the noise.
