### ISSUE TITLE
Support selective enablement of outline per file

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#427]
Today we can enable/disable the symbol provider with the `xml.symbols.enabled` preference on client side (very helpful for big file because vscode outline is very slow with big symbols).

But when you disable the symbol provider with this preference, all XML files even when there are little doesn't display the content of the outline. It's really shame.

To fix this problem, we could add a new preferences like `xml.symbols.disabled.patterns` which is an array of pattern file used to disable symbols if XML file match the pattern. To manage matching of pattern file, we could refactor the xml file association class https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/settings/XMLFileAssociation.java to an new class like FilePatternMatching class and XMLFileAssociation could extend it and new file like XMLSymbolsPatterns could extend it.

**Comment by NikolasKomonen** [comment]
I can work on this issue if no one else wants to do it.

**Comment by NikolasKomonen** [comment]
@fbricon @angelozerr Thoughts on using the name `xml.symbols.excluded` ?

**Comment by fbricon** [comment]
> @fbricon @angelozerr Thoughts on using the name `xml.symbols.excluded` ?

+1

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/lsp4xml/pull/432
