### ISSUE TITLE
Scanner does not handle unclosed tags well

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#45]
If a tag is not properly closed eg `<tag </tag>` the scanner will not be smart enough to recognise the start of a new tag.

The scanner should search for the closing tag, while also checking if it sees a new opening tag.
This will be helpful since it will indicate and un-closed tag to every service that uses the Scanner and will prevent incorrect Node structures, Incorrect Document Validations, Formatting...

At most the Scanner will return the new opening bracket Token (eg '<') instead of the wrong closing bracket Token.

**Comment by NikolasKomonen** [comment]
@angelozerr I will implement this for now, and we can test it later with your implementations of the services.

**Comment by angelozerr** [comment]
@NikolasKomonen I have already commited my tests. So if you changed pass tests, we will able to merge your work.

**Comment by angelozerr** [comment]
Can We close this issue ?
