### ISSUE TITLE
NPE in textDocument/definition in XSD files

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#488]
With an XSD document as simple as 
```xml
<?xml version='1.0'?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'>
</xs:schema>
```
In VS Code, when you ctrl+hover (or cmd+hover on Mac) over `schema` (to trigger textDocument/definition), an NPE is thrown by LSP4XML

**Comment by angelozerr** [comment]
@fbricon please review https://github.com/angelozerr/lsp4xml/pull/489/
