### ISSUE TITLE
xml.symbols.excluded does not work if document kept open

### ISSUE THREAD

**Issue by xorye** [angelozerr/lsp4xml#498]
![issue gif](https://raw.githubusercontent.com/xorye/gifs/master/new_issues/exclude.gif?token=AE3CR5MCEWHD6GMLAAJPX2S5ETWUA)

`xml.symbols.excluded` does not work if you keep the document open as a tab. 
You must either close the tab and open the document again, or edit the document for the 
`xml.symbols.excluded` settings to take effect.

This behaviour confused me at first.

**Comment by fbricon** [comment]
I don't think we can/should necessarily retrigger a symbol request. Just documenting the requirement to reload the document should suffice.

**Comment by angelozerr** [comment]
> I don't think we can/should necessarily retrigger a symbol request. Just documenting the requirement to reload the document should suffice.

IMHO I think we should support this issue since `xml.symbols.enabled` support this feature.

**Comment by fbricon** [comment]
Yeah but it's technically very different. When symbols are disabled globally, the server unregisters the feature from the client, so the client (vscode) makes the necessary updates automatically.
When the symbols are disabled **per** file, the client doesn't know it needs to reload the outline (the feature is still enabled). So we'd have to do some black magic on the client side to:
- detect the preference has changed (or wait for some event on the server side), 
- then programmatically reload the outline, if it's visible

**Comment by angelozerr** [comment]
Thanks for the clarification @fbricon. So I agree with you we should document that.
