### ISSUE TITLE
Enable ClientLogHandler with param

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#50]
Today ClientLogHandler is every time enabled. I don't know if it is the wished behaviour.

If we see the code of LogHelper, the initializationObject  cannot be never null (empty but not null)
```java
	public static void initializeRootLogger(LanguageClient newLanguageClient, Map<?, ?> initializationObject) {
		if(newLanguageClient == null || initializationObject == null) {
			return;
		}
```	

So the following code which enable )ClientHandler is done evry time.
```

	Logger logger = Logger.getLogger("");
		unregisterAllHandlers(logger.getHandlers());
		logger.setLevel(Level.SEVERE);
		logger.setUseParentHandlers(false);// Stops output to console

		try {
			logger.addHandler(LogHelper.getClientHandler(newLanguageClient));
		} catch (Exception e) {
			// TODO: handle exception
		}
```

To fix that, I think we should:

 * check like this:

`		if(newLanguageClient == null || initializationObject == null || initializationObject.isEmpty()) {`

 * use property 

    * `lsp4xml.logs.client.enabled` to know if client must be enabled or not
    *  `lsp4xml.logPath` should be perhaps replaced with `lsp4xml.logs.file.path`

What do you think about that?

**Comment by angelozerr** [comment]
A new idea that I have is to manage log configuration with JSON like this:

```json
{
  "logs": [
    "client": true,
    "file": "my-log-path-file"
  ]
}
```

instead of using flat properties. 

We could imagine to add another params for each plugin like:

```json
{
  "logs": [
    "client": true,
    "file": "my-log-path-file"
  ],
  "plugins": {
    "contentmodel": {
    },
    "emmet": {

    }
   }
}
```

What do you think about this idea?

**Comment by NikolasKomonen** [comment]
@angelo I made your recommended changes to the Logge. Also this is a good idea for the properties, I can work on this if you want.

**Comment by angelozerr** [comment]
Yes please, thanks

**Comment by fbricon** [comment]
see jdt.ls and how server preferences  are sent through initialization options
- https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request (see InitializationOptions.settings)

those settings are the same as those sent through didConfigurationChange. Ask @snjeza for more info if you need

**Comment by NikolasKomonen** [comment]
@fbricon alright I'll look into it, thanks

**Comment by angelozerr** [comment]
Indeed it was the idea that I had (do like jdt.ls). The main difference is that there is plugin extension. We need to add a plugin section with a Map. For instance in my case I need to configure catalog files for the contentmodel plugin.

**Comment by angelozerr** [comment]
@NikolasKomonen  I'm waiting for your work to have a config class (like jdt.ls) to configure catalog  https://github.com/angelozerr/lsp4xml/issues/38 Once you will commit your work, I will add plugin & catalog section in your class config.

**Comment by NikolasKomonen** [comment]
@angelozerr  Right now I'm working on other things, I can get to it in the next few days.

**Comment by angelozerr** [comment]
> @angelozerr Right now I'm working on other things, I can get to it in the next few days.

No pb @NikolasKomonen I will implement this issue.

**Comment by angelozerr** [comment]
@NikolasKomonen let me implement this issue please. I would like to avoid using Map for settings. I'm experimenting something otherwise I will do like you.
