### ISSUE TITLE
xs:import code action inserting inside tag name

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#541]
After clicking the xs:import tag name a selecting the attribute name codeaction it will insert the text
inside the name instead of after it.

@xorye I think this was something you worked on.

![codeActionError](https://user-images.githubusercontent.com/32624665/61739728-0809cd00-ad5b-11e9-9671-1183a9508ce2.gif)

**Comment by angelozerr** [comment]
@xorye I'm not sure with that, but I think you should use `diagnostic.getRange() ` instead of using `range`

**Comment by angelozerr** [comment]
@xorye  or @NikolasKomonen  could you try to fix this issue please by using `diagnostic.getRange()`
