### ISSUE TITLE
Standalone release of 0.8.0?

### ISSUE THREAD

**Issue by fannheyward** [angelozerr/lsp4xml#550]
Hello, 0.8.0 was released two days ago, but I can't find it in https://dl.bintray.com/lsp4xml/releases/org/lsp4xml/org.eclipse.lsp4xml/ or https://jcenter.bintray.com/org/lsp4xml/org.eclipse.lsp4xml/ .

How can I get the latest version of standalone release, the `org.eclipse.lsp4xml-x.y.z-uber.jar` file?

Thanks.

**Comment by fannheyward** [comment]
Additional info why I need standalone release:

I built a coc.nvim extension, https://github.com/fannheyward/coc-xml, which can use lsp4xml in vim/nvim with _almost_ full features of vscode-xml.

vscode-xml has packaged the lsp4xml-uber.jar into the extension, but my extension didn't packaged it, instead download from dl.bintray.com, so I need the standalone release.

Which way do you recommend to get the lsp4xml server? Packaged it into extension or download?

**Comment by fbricon** [comment]
Sorry, the travis build failed because of a new behavior in Travis. We need apply a fix and to retag 0.8.0

**Comment by fbricon** [comment]
0.8.0 binaries published to bintray https://dl.bintray.com/lsp4xml/releases/org/lsp4xml/org.eclipse.lsp4xml/0.8.0/
