### ISSUE TITLE
Validation Error Message Fails on Certain Cases

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#553]
First found from this issue: https://github.com/redhat-developer/vscode-xml/issues/177#issuecomment-520132932

The line of code that looks like this, https://github.com/angelozerr/lsp4xml/blob/fee585992ab5c1748708cf92aada4c7f01c7f220/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/contentmodel/participants/XMLSchemaErrorCode.java#L155

fails because the type we are casting it to is not always a string in certain cases.

Instead use the toString() method, make a StringUtils method to handle this issue.

**Comment by NikolasKomonen** [comment]
@skjardenCode

Does this fix the issue you were having in https://github.com/redhat-developer/vscode-xml/issues/177#issuecomment-520132932?

![image](https://user-images.githubusercontent.com/32624665/62972921-1c356d00-bde3-11e9-8c0d-ac6c736f88a8.png)

**Comment by angelozerr** [comment]
@NikolasKomonen I think you have fixed the issue.
