### ISSUE TITLE
Add support for `textDocument/documentLink`

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#56]
Add support for `textDocument/documentLink` https://microsoft.github.io/language-server-protocol/specification#textDocument_documentLink for extension.

One extension for web (web.xml) could manage hyperlink for welcome-file to open it:

```xml
<welcome-file-list>
     <welcome-file>index.jsp</welcome-file>
     <welcome-file>index.html</welcome-file>
</welcome-file-list>
```

One extension for String could manage hyperlink for class to open the Java class:

```xml
<bean class="MyClass" />
```

**Comment by fbricon** [comment]
Is it complete now? Because we can navigate to schemas defined in xsi:noNamespaceSchemaLocation for instance.

web.xml hyperlink is a specific use case I wouldn't worry about for now.

**Comment by angelozerr** [comment]
> Is it complete now? 

yes extension is done

> Because we can navigate to schemas defined in xsi:noNamespaceSchemaLocation for instance.

exactly and it exists test for this feature at https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/extensions/contentmodel/XMLSchemaDocumentLinkTest.java
