### ISSUE TITLE
Add support for `textDocument/codeAction`

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#57]
Add support for `textDocument/codeAction` https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction :

 * to provide quick fix to close a tag which is not closed
 * for extension

**Comment by NikolasKomonen** [comment]
@angelozerr this is great, good work

**Comment by angelozerr** [comment]
It misses some code actions, I think, but we will create new issue for that. Now we can add any code actions with extensions.
