### ISSUE TITLE
Found the limitation of getCurrentAttributeName() method of AbstractPositionRequest class

### ISSUE THREAD

**Issue by Seiphon** [angelozerr/lsp4xml#583]
Hi @angelozerr and @fbricon 

I found a limitation for getCurrentAtrributeName() method of AbstractPositionReqest class.

When I try to support hover feature for attribute name, I found it's difficult to get correct attribute name.
`
@Override
public String getCurrentAttributeName() 
{
	return currentAttributeName;
}
`

It because before we use get method, we should set the attribute name first (Like XMLCompletions.doComplete method does).

How about try to get the attribute name by DOM first. Like getCurrentTag() does.
Like follows:

`@Override`
`public String getCurrentAttributeName() {`
`        if (node != null && node.isAttribute() && ((DOMAttr) node).getName() != null) {`
`                return ((DOMAttr) node).getName();`
`        }`
`        return currentAttributeName;`
`}`

**Comment by Seiphon** [comment]
Please see this PR https://github.com/angelozerr/lsp4xml/pull/584.

**Comment by angelozerr** [comment]
@Seiphon please add a test with your usecase.

**Comment by Seiphon** [comment]
> @Seiphon please add a test with your usecase.

Hi @angelozerr , I added a test on AggregetedHoverValuesTest. If it's not allowable, I will add a new test class for it.

**Comment by angelozerr** [comment]
Fixed with https://github.com/angelozerr/lsp4xml/pull/584
