### ISSUE TITLE
DTD hover/completion support for documentation

### ISSUE THREAD

**Issue by Seiphon** [angelozerr/lsp4xml#585]
Hi @angelozerr and @fbricon ,

I found when do hover and code completion, the prompt information is not expected.
How do you think about this issue?
Please see the picture:
hover:
![Screenshot (33)](https://user-images.githubusercontent.com/24595644/67554182-7175ef00-f741-11e9-8261-232a7dfc04b7.png)
code completion:
![Screenshot (28)](https://user-images.githubusercontent.com/24595644/67554258-9bc7ac80-f741-11e9-958e-2b92ccfcc0ba.png)

The expected result should like follows (from Eclipse original XML editor):
hover:
![Screenshot (32)](https://user-images.githubusercontent.com/24595644/67554359-cfa2d200-f741-11e9-814a-79e5ef09b150.png)
code completion:
![Screenshot (29)](https://user-images.githubusercontent.com/24595644/67554379-d9c4d080-f741-11e9-8dee-6fa380f4e1ae.png)

cc @jtydhr88

**Comment by fbricon** [comment]
is this a follow up on #577? Could you provide a sample document reproducing this issue?

**Comment by Seiphon** [comment]
No, this is a independent issue. I will upload a service.xml for you to test.

[service.zip](https://github.com/angelozerr/lsp4xml/files/3771195/service.zip)

**Comment by fbricon** [comment]
I see. The comments before the element declaration in the DTD is expected to serve as documentation:

```xml
<!--
An entity usually represents a business facade and a table in the database. If
an entity does not have any columns, then it only represents a business facade.
The Service Builder will always generate an empty business facade POJO if it
does not exist. Upon subsequent generations, the Service Builder will check to
see if the business facade already exists. If it exists and has additional
methods, then the Service Builder will also update the SOAP wrappers.

If an entity does have columns, then the value object, the POJO class that
is mapped to the database, and other persistence utilities are also generated
based on the order and finder elements.
-->
<!ELEMENT entity (column*, localized-entity?, order?, finder*, reference*, tx-required*)>
```

@angelozerr should know better how it should be to implemented

**Comment by angelozerr** [comment]
At first I noticed that hover has bad renderer with LSP4E. I have never found time to study this case.

You can see the trouble in 

![Screenshot (33)](https://user-images.githubusercontent.com/24595644/67554182-7175ef00-f741-11e9-8261-232a7dfc04b7.png)

Why we cannot see the whole source link? LSP4E should support markdown, but I'm not sure LSP4XML receive this capability. Is a problem with markdown converter (mylin markdown is used for that)?

> The comments before the element declaration in the DTD is expected to serve as documentation:

Ok the main problem that I see is that we don't collect documentation for DTD. 

Today we don't support documentation for DTD https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/dtd/contentmodel/CMDTDElementDeclaration.java#L94

Today we collect hierarchy element https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/extensions/dtd/contentmodel/CMDTDDocument.java#L133

I think to manage comment, we should collect it 

```java
public class CMDTDDocument {

       @Override
	public void comment(XMLString text, Augmentations augs) throws XNIException {
                // TODO: Here we must attach the text comment with the next element declaration          
		super.comment(text, augs);
	}

}
```

@Seiphon is there something that you could try it?

**Comment by angelozerr** [comment]
@Seiphon for the problem with LSP4E, https://bugs.eclipse.org/bugs/show_bug.cgi?id=552429 was merged and now you should see an hyperlink to open the XML Schema:

![LSP4XMLMarkdown](https://user-images.githubusercontent.com/1932211/67578696-48565e00-f743-11e9-9221-bf413bc00110.png)

**Comment by Seiphon** [comment]
Thanks @angelozerr , so the next step is to impletement the collection of DTD documentation, right?
I will try to work on it this week.

**Comment by angelozerr** [comment]
> so the next step is to impletement the collection of DTD documentation, right?
I will try to work on it this week.

Exactly! It's just an idea, if you find a better mean please do that. Please write test too with this feature. To do that, I suggest you you write your test in `org.eclipse.lsp4xml.extensions.contentmodel.DTDHoverExtensionsTest` like we have for XSD https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/extensions/contentmodel/XMLSchemaHoverExtensionsTest.java

**Comment by Seiphon** [comment]
Hi @angelozerr , sorry for delay. I implement it by my understanding on this pr https://github.com/angelozerr/lsp4xml/pull/592 . If there is something not correct, please let me know, I will update it.

**Comment by angelozerr** [comment]
@Seiphon your PR is ready to merge. Once you will fix commit description https://github.com/angelozerr/lsp4xml/pull/592#issuecomment-550358031 I would like to merge your great PR

Thanks!
