### ISSUE TITLE
Use another package name than `org.eclipse.xml`

### ISSUE THREAD

**Issue by mickaelistria** [angelozerr/lsp4xml#6]
The package name is `org.eclipse.xml...`. Typical Eclipse projects use an `org.eclipse.<projectName>` as root package. To avoid necessary further refactoring when moving to Eclipse.org, we should consider deciding of a projectName already and adopt this in package name asap.

**Comment by angelozerr** [comment]
What about **org.eclipse.lsp4xml** ?

**Comment by mickaelistria** [comment]
no objection here.

**Comment by angelozerr** [comment]
@fbricon @apupier @NikolasKomonen what do you think about this name? Other suggestions?

**Comment by angelozerr** [comment]
@fbricon @apupier @NikolasKomonen could you give me your opinion please. I would like change package names. Thanks!

**Comment by angelozerr** [comment]
Done I have refactor the project with `org.eclipse.lsp4xml`

**Comment by NikolasKomonen** [comment]
@angelozerr sorry I havent replied to anything, these notifications are
delayed for me for some reason. Otherwise, everything looks great!

**Comment by angelozerr** [comment]
No problem @NikolasKomonen ! Glad this name pleases you. Please note that I have sent you an invitation to become a collaborator.
