### ISSUE TITLE
Visual Code cursor jumping backward then forward for any keyboard event

### ISSUE THREAD

**Issue by daveb-501commons** [angelozerr/lsp4xml#601]
Several people are getting issues w/ Visual Studio code after a recent upgrade.
https://github.com/microsoft/vscode/issues/86966

The issue on my visual code setup is related to this XML Red Hat upgrade on 0.10.0 Dec 13, 2019.

If I disable this extension then typing works fine again.  This is happening in not just the XML files but any file in my Visual Studio code project.

**Comment by angelozerr** [comment]
Thank's @daveb-501commons for reporting this issue. 

@fbricon we need to fix quickly this issue (fix or disable the mirror cursor by default).

**Comment by fbricon** [comment]
Closing as it's a vscode-xml issue (https://github.com/redhat-developer/vscode-xml/issues/211)
