### ISSUE TITLE
Unregister language server extension on LS shutdown

### ISSUE THREAD

**Issue by AObuchow** [angelozerr/lsp4xml#605]
For the LemMinX/lsp4xml maven extension testing suite, it's required that `IXMLExtension.stop()` be called when the LS gets shutdown. In our case, file locks for Maven index files get released when the extension is unregistered. However, currently the extensions aren't unregistered when the server is shutdown.

Unless there is a suitable workaround, having XML LS extensions get unregistered on LS shutdown would be greatly appreciated.

**Comment by AObuchow** [comment]
Also I can submit a seperate bug for this, but I just noticed that the `ExtensionRegistry.unregister... ` methods [seem to call `List.add()`](https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/services/extensions/XMLExtensionsRegistry.java#L206). Is this intentional?

**Comment by fbricon** [comment]
> Also I can submit a seperate bug for this, but I just noticed that the `ExtensionRegistry.unregister... ` methods [seem to call `List.add()`](https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/services/extensions/XMLExtensionsRegistry.java#L206). Is this intentional?

definitely a bug. All methods were copied/pasted, all unregister methods are wrong, so yes please open another ticket.

As for your initial question, I'll let @angelozerr respond

**Comment by angelozerr** [comment]
> definitely a bug. All methods were copied/pasted, all unregister methods are wrong, so yes please open another ticket.

Exactly, we don't use this feature @AObuchow please create a PR for fixing that.

> Unless there is a suitable workaround, having XML LS extensions get unregistered on LS shutdown would be greatly appreciated.

Unregister extension is not supported (just coding some unregister method on the start of the project, but nothing else).

PLease create a PR for that, I suggest you that you add:

 * a `dispose `method in the XMLExtensionRegistry which loops for each extensions and call the existing unregisterExtension
 * call this dispose method on the XML Language server shutdown.

**Comment by AObuchow** [comment]
> > Also I can submit a seperate bug for this, but I just noticed that the `ExtensionRegistry.unregister... ` methods [seem to call `List.add()`](https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/services/extensions/XMLExtensionsRegistry.java#L206). Is this intentional?
> 
> definitely a bug. All methods were copied/pasted, all unregister methods are wrong, so yes please open another ticket.
> 
> As for your initial question, I'll let @angelozerr respond

Sounds good, I'll open a ticket and submit a PR

**Comment by AObuchow** [comment]
> PLease create a PR for that, I suggest you that you add:
> 
> * a `dispose `method in the XMLExtensionRegistry which loops for each extensions and call the existing unregisterExtension
> * call this dispose method on the XML Language server shutdown.

Sounds good, will submit a PR momentarily.
