### ISSUE TITLE
Comments are not considered in Formatting

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#74]
The XMLScanner is setup for comments, but it is not handled in XMLFormatting, formatting will remove the comments. 

To fix add consideration of comments in XMLParser

**Comment by angelozerr** [comment]
For XMLCompletions, XMLHighlighting it is working for me. What do you want to do with XMLParser?

For XMLFormatting, the format remove the comments. I think this issue should be renamed too "format should keep comments". But maybe I missed something?

**Comment by NikolasKomonen** [comment]
@angelozerr You're right, I forgot that Completions used the Scanner and from other IDE's I guess comments dont need highlighting. Ill update this.
