### ISSUE TITLE
Range formatting is ignoring the rest of the document's indentation

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#76]
When formatting a selection, the whole selection is formatted against the 1st column, ignoring the rest of the document's indentation. See:

![xml-format-region](https://user-images.githubusercontent.com/148698/44673241-ef811d80-a9f8-11e8-8937-a65c20cc646f.gif)

In Java for instance, the selection is also formatted against the rest of the document:

![java-format-region](https://user-images.githubusercontent.com/148698/44673455-98c81380-a9f9-11e8-8778-845df971d70f.gif)

**Comment by angelozerr** [comment]
I will fix it since I have already done that for completion.

**Comment by fbricon** [comment]
@angelozerr are you still looking at that one or should we assign it to @NikolasKomonen. Because that makes range formatting almost useless

**Comment by angelozerr** [comment]
I'm fixing https://github.com/angelozerr/lsp4xml/issues/117 and after I will see it.

**Comment by fbricon** [comment]
cool, thanks
