### ISSUE TITLE
Basic Validation response sent twice if auto save is on

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#77]
Not sure about schema validation

**Comment by angelozerr** [comment]
> Not sure about schema validation

It should do the same thing. Have you this same problem with other language server (ex : HTML Language Server)?

**Comment by fbricon** [comment]
if validation is triggered on document change and document save, then it makes sense to see validation being triggered twice.

**Comment by angelozerr** [comment]
> if validation is triggered on document change and document save, then it makes sense to see validation being triggered twice.

Indeed it was my though too, but I would like just to check that thi sbehaviour is the same with other language server

**Comment by angelozerr** [comment]
Can we close this issue?
