### ISSUE TITLE
[Request] Document Formatting

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#8]
It should be nice to have a formatting XML support. Format should be done:

 * for the whole XML document
 * for selected content of XML document

There are 2 strategies to do that:

 * use standard XML Outputformat. It's the easy mean but it requires that XML is well done.
 * use the XMLDocument instance created by the tolerant XML parser. IMHO I think it's the better mean, but it's more hard. WTP / XML Editor uses this strategy. (see https://github.com/eclipse/webtools.sourceediting/blob/master/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/formatter/XMLFormatterFormatProcessor.java)

We need too defines formatting preferences. Here the WTP/ XML Editor preferences:

![image](https://user-images.githubusercontent.com/1932211/42088189-056563ec-7b99-11e8-9805-7436200bd4f4.png)

You can find it at https://github.com/eclipse/webtools.sourceediting/blob/master/xml/bundles/org.eclipse.wst.xml.core/src/org/eclipse/wst/xml/core/internal/formatter/XMLFormattingPreferences.java

**Comment by angelozerr** [comment]
@NikolasKomonen  I have just initialize the formatter that iy can now implement. You can see quicly https://github.com/Microsoft/vscode-html-languageservice/blob/master/src/services/htmlFormatter.ts which uses beautify.

**Comment by angelozerr** [comment]
@NikolasKomonen @fbricon I'm doing a big refactoring to clean API. Please wait my push before working on some issues. Sorry for that -(

**Comment by angelozerr** [comment]
This issue requires tests. @NikolasKomonen do you want to work on this issue?

**Comment by angelozerr** [comment]
@NikolasKomonen is there any chance that you work on test and fix bug with prolog https://github.com/angelozerr/lsp4xml/issues/43#issuecomment-411187148

**Comment by NikolasKomonen** [comment]
@angelozerr For sure, Ill work on [#43](https://github.com/angelozerr/lsp4xml/issues/43#issuecomment-411187148) and make sure this works with it.

**Comment by angelozerr** [comment]
Cool, thanks!

**Comment by angelozerr** [comment]
I close this issue since https://github.com/NikolasKomonen/xml-languageserver/commit/eba46be2e32ae89205d41b838633d453abf3c692 fixes the prolog formatti,g problem.

Thanks @NikolasKomonen ! Please see https://github.com/angelozerr/lsp4xml/issues/67 to give settings for format.

**Comment by angelozerr** [comment]
Here a demo:

![](https://github.com/angelozerr/lsp4xml/wiki/images/XMLFormattingDemo.gif)

See wiki at https://github.com/angelozerr/lsp4xml/wiki/Features#format for more information
