### ISSUE TITLE
Support for XML associations

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#80]
Gives the capability to assocoiate a give file (ex : `.project`, `.classpath`) with a XML Schema to benefit with compeltion and validatioin. Indeed Eclispe files `.project`, `.classpath` doesn't define an XML Schema in their root. Associate a XMl Schema with a given file name pattern could be helpful.

The question is about file pattern. We could manage at hand '*' pattern like https://github.com/microclimate-devops/xml-language-server/blob/master/server/xml-server/src/com/ibm/ctools/ls/xml/XMLLanguageServer.java#L119 does but I find it's a little limitaed.

My idea @fbricon @NikolasKomonen is to support minimatch pattern with my Minimatch port in Java https://github.com/angelozerr/minimatch.java

Are you OK with this new dependency?

**Comment by fbricon** [comment]
@angelozerr Minimatch's original license is ISC, your didn't retain the license/copyright in your port. I think the license change is fine as MIT is close to ISC, but IANAL. The copyright attribution is more problematic I think. So I'd prefer having the opinion of a legal professional here.

**Comment by angelozerr** [comment]
> The copyright attribution is more problematic I think. So I'd prefer having the opinion of a legal professional here.

-( My job was to translate minimatch JS in Java. I don't use minimatch.js, minimatch.java is a pur Java code.

**Comment by angelozerr** [comment]
This issue was implemented and I'm using Java7 PathMatcher with glob pattern. 

See wiki https://github.com/angelozerr/lsp4xml/wiki/Configuration#file-associations for more information.
