### ISSUE TITLE
Add autoclose tags

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#82]
When an opening tag is written eg: `<root>` the closing tag `</root>` should be automatically inserted.

The HTML language server does this with their own custom request.

References:

- https://github.com/Microsoft/vscode/blob/f707828426bd87e88c17d2da34f2ceed0019d8bd/extensions/html-language-features/client/src/htmlMain.ts#L19

-  https://github.com/Microsoft/vscode/blob/f707828426bd87e88c17d2da34f2ceed0019d8bd/extensions/html-language-features/client/src/htmlMain.ts#L75

- https://github.com/Microsoft/vscode/blob/f707828426bd87e88c17d2da34f2ceed0019d8bd/extensions/html-language-features/client/src/tagClosing.ts

**Comment by angelozerr** [comment]
@NikolasKomonen I think it's an issue for vscode-xml (client side) and nor for the server side. The links are about vscode client not about server side. If it that, please close this issue and move it to vscode-xml project.

**Comment by angelozerr** [comment]
Ok thanks guys for your explanation.

**Comment by angelozerr** [comment]
See wiki at https://github.com/angelozerr/lsp4xml/wiki/Language-Server-Protocol-Extensions

**Comment by fbricon** [comment]
@angelozerr have you checked how it behaves with emmet support?
