### ISSUE TITLE
Clean XMLDocument model to use getter/setter

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#84]
The Node class https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/main/java/org/eclipse/lsp4xml/model/Node.java declare their field as public (ex : node.tag) . This code is today like this because it comes from vscode html language service. It should set tag as private and provide getTag, setTag.

**Comment by angelozerr** [comment]
@frrebricon @NikolasKomonen it's a big work which requires a big refactoring. Tell me when you wish I do that in order to avoid annoying you.

**Comment by fbricon** [comment]
@NikolasKomonen is the one affected by it. But it shouldn't take too long to fix, even though it probably touches many files, since that kind of refactoring is well-handled by modern IDEs

**Comment by angelozerr** [comment]
> since that kind of refactoring is well-handled by modern IDEs

I mean change Node#tag by Node#getTag(),  Node#setTag(String tag). are you sure IDE can manage that?

**Comment by fbricon** [comment]
@angelozerr can we close that one now?

**Comment by angelozerr** [comment]
No, it's not fisnished, sorry -( I will push soon a big refactoring.

**Comment by angelozerr** [comment]
Now we have a clean XMLDocument,Node  structure. All tests are passed in my Windows OS.

Hope I have not broken something. Please create issues of you find bugs.
