### ISSUE TITLE
Auto Complete/ Completion for XML Prolog

### ISSUE THREAD

**Issue by NikolasKomonen** [angelozerr/lsp4xml#85]
When `<?` or `<?xml` is typed give the option to complete the rest

**Comment by angelozerr** [comment]
Do you want to Work on this issue ?

**Comment by NikolasKomonen** [comment]
@angelozerr sure

**Comment by angelozerr** [comment]
Thanks @NikolasKomonen

**Comment by fbricon** [comment]
Completion is only available once `<?xml` is typed. Should start at `<?` when on the 1st line of the document

**Comment by fbricon** [comment]
So now we have completion at either `<?` or `<?xml` , but nothing in between
