### ISSUE TITLE
Same error reported twice on unclosed tag

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#87]
Try this snippet:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<site>
   <bundle id="foo" version="1.0.0.qualifier"/
</site>
```
Same error message is reported twice, at the beginning and the end of the offending tag:
- `Element type "bundle" must be followed by either attribute specifications, ">" or "/>".` (3, 5)
- `Element type "bundle" must be followed by either attribute specifications, ">" or "/>".` (3, 69)

<img width="820" alt="screen shot 2018-09-02 at 7 07 51 pm" src="https://user-images.githubusercontent.com/148698/44961721-b60e4d80-aee3-11e8-8657-05ead97afc91.png">

**Comment by angelozerr** [comment]
I cannot reproduce with LSP4e? If you close your XML file and open it, have you the same problem?

**Comment by fbricon** [comment]
My bad, the problem was caused by having both redhat.vscode-xml and gorkem.vscode-xml extensions installed. Closing.

**Comment by angelozerr** [comment]
No problem, very cool news:)
