### ISSUE TITLE
Duplicate completion proposals

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#88]
Completion proposals to close tags are duplicated:

<img width="685" alt="screen shot 2018-09-02 at 7 17 15 pm" src="https://user-images.githubusercontent.com/148698/44961795-ee625b80-aee4-11e8-9b5a-0db45a2c83bd.png">

**Comment by angelozerr** [comment]
That's strange, I cannot reproduce with LSP4E? Could you check the LSP trace in VSCode to check that it's a problem from XML Language Server?

**Comment by fbricon** [comment]
My bad, the problem was caused by having both redhat.vscode-xml and gorkem.vscode-xml extensions installed. VSCode couldn't know one was the evolution of the other. Closing

**Comment by angelozerr** [comment]
No problem, very cool news:)
