### ISSUE TITLE
Processing instruction errors not reported if followed by another processing instruction

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#89]
Given a document containing 2 processing instructions (PI), the 1st malformed PI is not reported as an error 
```xml
<?xml-stylesheet type="text/xsl" href="style.xsl"? //should fail here
<?xml-stylesheet type="text/css" href="style.css"?>
```

**Comment by angelozerr** [comment]
I'm afraid that it's not possible to fix this issue, since Xerces doesn't report this error (you will see that this error is ignored in WTP XML Editor too).

**Comment by fbricon** [comment]
@NikolasKomonen can you check on intellij or netbeans please? I'm not gonna install those on my shitty 4GB ram laptop

**Comment by NikolasKomonen** [comment]
@fbricon Intellij does not report this error either. :smile:
