### ISSUE TITLE
[Request] Document Symbols

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#9]

**Comment by angelozerr** [comment]
This feature is implemented. I need to add tests.

**Comment by NikolasKomonen** [comment]
@angelozerr Can this be closed now?

**Comment by angelozerr** [comment]
Yes sure, thanks @NikolasKomonen for your PR.

**Comment by angelozerr** [comment]
Done:

![xmldocumentsymbolsinoutline](https://user-images.githubusercontent.com/1932211/43759743-7a2a0656-9a20-11e8-8233-5f797b262f1e.png)

See wiki at https://github.com/angelozerr/lsp4xml/wiki/Features#document-symbols
